Workiva/over_react_codemod

CHANGELOG.md
README.md
pubspec.yaml

* [Add migrater](https://github.com/Workiva/over_react_codemod/pull/1)
* [AF-1928 Add suggestors for PropsMeta changes](https://github.com/Workiva/over_react_codemod/pull/2)
* [AF-2152: add more tests to cover additions made in AF-1928](https://github.com/Workiva/over_react_codemod/pull/4)
* [AF-1917: Make over_react_codemod script idempotent](https://github.com/Workiva/over_react_codemod/pull/5)
* [AF-3102 AF-2797 AF-1943 Update codemod to match final transition boilerplate](https://github.com/Workiva/over_react_codemod/pull/6)
* [AF-3591 Add OSS license texts](https://github.com/Workiva/over_react_codemod/pull/7)
* [AF-3592 Add OSS license header to all source files](https://github.com/Workiva/over_react_codemod/pull/8)
* [AF-3101 Add support for …

AF-3863 Release over_react_codemod 1.0.0

---

CHANGELOG.md
lib/src/dart2_suggestors/ui_factory_ignore_comment_remover.dart
lib/src/dart2_suggestors/ui_factory_initializer.dart
test/dart2_suggestors/ui_factory_ignore_comment_remover.suggestor_test
test/util.dart

- No longer emits an empty patch when the ignore comment precedes the entire factory declaration
- testSuggestorsDir() util now also asserts that no empty patches were emitted
@corwinsheahan-wf @sebastianmalysa-wf @georgelesica-wf @maxwellpeterson-wf

AF-3985 Fix a bug with the UiFactoryIgnoreCommentRemover

---

CHANGELOG.md
lib/src/dart2_suggestors/generated_part_directive_adder.dart
lib/src/dart2_suggestors/generated_part_directive_ignore_remover.dart
lib/src/dart2_suggestors/needs_over_react_library_collector.dart
lib/src/dart2_suggestors/orcm_ignore_remover.dart
lib/src/executables/dart2_upgrade.dart
test/dart2_suggestors/generated_part_directive_adder.suggestor_test
test/dart2_suggestors/generated_part_directive_ignore_remover.suggestor_test
test/dart2_suggestors/orcm_ignore_remover.suggestor_test
test/suggestors_test.dart

Two more suggestors for the `dart2_upgrade` codemod when not retaining backwards-compatibility:
- Removing any `// orcm_ignore` comments. These are only necessary to prevent the codemod from failing when running in the `--fail-on-changes` mode for instances that were being flagged as false positives.
- Removing the `// ignore: uri_has_not_been_generated` comment that precedes all `.over_react.g.dart` part directives.
@corwinsheahan-wf @sebastianmalysa-wf @smaifullerton-wk @seanburke-wf @maxwellpeterson-wf

CPLAT-4307 Add two comment removing suggestors to dart2_upgrade

---

lib/src/dart2_suggestors/ui_factory_ignore_comment_remover.dart
lib/src/executables/dart2_upgrade.dart
test/dart2_suggestors/ui_factory_ignore_comment_remover.suggestor_test

@maxwellpeterson-wf reported a bug with the codemod where it is possible for certain suggestors to suggest overlapping patches, which is disallowed by the codemod runner. To avoid this, we can simply break up the suggestor list into a few more "phases" that run sequentially. In particular, the cleanup suggestors that remove the backwards-compat-only stuff can be run in their own aggregate suggestor after the other suggestors.
Also included an improvement to the UI factory ignore comment remover that rewrites less (meaning that if you have a factory with a really large doc comment on it, the suggestor won't include that in the diff).

CPLAT-4451 Reorder suggestors and improve the UI factory ignore remover

---

CHANGELOG.md
lib/src/executables/dart2_upgrade.dart
pubspec.yaml

* [CPLAT-4307 Add two comment removing suggestors to dart2_upgrade](https://github.com/Workiva/over_react_codemod/pull/25)
* [CPLAT-4451 Reorder suggestors and improve the UI factory ignore remover](https://github.com/Workiva/over_react_codemod/pull/26)
Requested by: @evan.weible
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_codemod/compare/1.0.2...Workiva:release_over_react_codemod_1.1.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react_codemod/compare/1.0.2...1.1.0

CPLAT-4097 Release over_react_codemod 1.1.0

---

lib/src/react16_suggestors/constants.dart
lib/src/react16_suggestors/react_dom_render_migrator.dart
lib/src/util/component_usage.dart
pubspec.yaml
test/react16_suggestors/react_dom_render_migrator_test.dart
test/util.dart

- To ensure a smooth update to React 16, this codemod needs to:
- Wrap `react_dom.render` calls in ErrorBoundary to ensure the component tree isn't unmounted when an error occurs.
- Update references to the return value of `react_dom.render` to use a callback ref instead.
- Add checkbox comments to manually verify that components rendered by `react_dom.render` safely use existing refs and refs added by the codemod to ensure that they won't break when the ref becomes async in React 16.
- These updates do not need to be made in tests.
- Add codemods to make `ErrorBoundary` and `react_dom.render` updates.
- Add test coverage.
@kealjones-wk …

CPLAT-6573 React 16 ErrorBoundary / react_dom.render Codemod

---

lib/src/component2_suggestors/componentdidupdate_migrator.dart
lib/src/component2_suggestors/componentwillmount_migrator.dart
lib/src/executables/component2_upgrade.dart
pubspec.yaml
test/component2_suggestors/componentdidupdate_migrator_test.dart
test/util.dart

An optional `snapshot` argument needs to be added to `componentDidUpdate` to be compatible with UiComponent2.
- Add suggestor that adds an optional `snapshot` argument to `componentDidUpdate`.
- Write tests.
@kealjones-wk @aaronlademann-wf @joebingham-wk @greglittlefield-wf 

CPLAT-6812 Add optional snapshot arg to componentDidUpdate

---

lib/src/react16_suggestors/react_style_maps_updater.dart
test/react16_suggestors/react_style_maps_updater_test.dart

I ran into a couple edge cases when testing the codemod on graph_app that caused extra style map comments to be added.
- Don't insert comments for things like `style.width = ...`; the `.width` indicates a DOM API since we don't have typed maps for style maps with `width` getters.
- This cuts down on a lot of comments in places where they're mutating styles with the DOM API
- Act upon nested style maps, as a side effect of updating cascade filtering logic for the bullet above
- Don't insert comments for interpolated strings that add known CSS units
- Don't insert comments for `toRem`/`toPx` calls
- Don't codemod CSS properties that are unitless (e.g., `zIndex`) or don't represent numbers (e.g., `display`)
- Don't codemod when `style` is cascaded on instantiation expressions with `new`, …

CPLAT-7029 Fix style map codemod edge cases

---

lib/src/dart2_suggestors/pubspec_over_react_upgrader.dart
lib/src/react16_suggestors/pubspec_react_upgrader.dart
test/dart2_suggestors/pubspec_over_react_upgrader_test.dart
test/react16_suggestors/pubspec_react_updater_test.dart

An unexpected issue was found when testing the codemod. If you run the react16_upgrade when it would try and parse the version of a dependency found in `dependency_overrides`, (aka the version value was like "git:" and/or "path: ../".
- Added a try that wraps the version parsing and in the catch return if we find "git:" or "path:" in the message of the error.
- Added regression tests for `dependency_overrides` with git and path overrides  …

CPLAT-7372: Fix errors caused by trying to parse versions from dependency overrides

---

CHANGELOG.md
pubspec.yaml

* [CPLAT-6936 Add flag to skip components that codemod can only partially upgrade](https://github.com/Workiva/over_react_codemod/pull/42)
* [CPLAT-7372: Fix errors caused by trying to parse versions from dependency overrides](https://github.com/Workiva/over_react_codemod/pull/50)
Requested by: @kealjones-wk
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_codemod/compare/1.2.0...Workiva:release_over_react_codemod_1.3.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react_codemod/compare/1.2.0...1.3.0

RM-57798 Release over_react_codemod 1.3.0

---

lib/src/dart2_suggestors/pubspec_over_react_upgrader.dart
lib/src/react16_suggestors/pubspec_react_upgrader.dart
lib/src/util.dart
test/shared_pubspec_tests.dart
test/util_test.dart

If a version of over_react or react was set to "any" it would throw:
```
➜ pub global run over_react_codemod:react16_upgrade --verbose
searching...
[FINE] codemod: file: functional_tests/import_integration/pubspec.yaml
[SEVERE] codemod: Suggestor.generatePatches() threw unexpectedly.
NoSuchMethodError: The method '>=' was called on null.
Receiver: null
Tried calling: >=(Instance of 'Version')
dart:core                                                                               Object.noSuchMethod
package:over_react_codemod/src/util.dart 363:26                                         shouldUpdateVersionRange
package:over_react_codemod/src/dart2_suggestors/pubspec_over_react_upgrader.dart 77:13  PubspecOverReactUpgrader.generatePatches
dart:core …
```

Fix for version "any"

---

lib/src/component2_suggestors/class_name_and_annotation_migrator.dart
lib/src/component2_suggestors/component2_constants.dart
lib/src/component2_suggestors/component2_utilities.dart
lib/src/constants.dart
lib/src/react16_suggestors/react16_utilities.dart
test/component2_suggestors/class_name_and_annotation_migrator_test.dart
test/component2_suggestors/component2_utilities_test.dart

`UIComponent`s with mixins could potentially be mixing in a class that implement component lifecycle methods that are unsupported in `Component2`.
1. When [the `--no-partial-upgrades` flag](https://github.com/Workiva/over_react_codemod/pull/42) is `false`, add a `/// FIXME` comment to the component that has one or more mixins.
2. When [the `--no-partial-upgrades` flag](https://github.com/Workiva/over_react_codemod/pull/42) is `true`, skips the upgrade for the component that has one or more mixins.
Add logic to handle components with mixin(s) when upgrading to `UiComponent2`.
Please review: @greglittlefield-wf @kealjones-wk @sydneyjodon-wk @joebingham-wk 
- …

CPLAT-7393 Add logic to handle components with mixin(s)

---

bin/react16_consumer_overlay_update.dart
lib/src/component2_suggestors/component2_utilities.dart
lib/src/executables/react16_consumer_overlay_update.dart
lib/src/react16_suggestors/consumer_overlay_migrator.dart
pubspec.yaml
test/react16_suggestors/consumer_overlay_migrator_test.dart

To aid in upgrading users, we should expose a codemod that migrates consumers.
- Set up new executable `react16_consumer_overlay_update`
- Add suggestor that, in component usages:
- Replaces `..overlay = …` with `..overlay2 = …`
- Replaces `..isOverlay = …` with `..isOverlay2 = …`
- Removes `..useLegacyPositioning = …`
- Write tests
@kealjones-wk @aaronlademann-wf @greglittlefield-wf @joebingham-wk 
- `pub global run over_react_codemod:react16_consumer_overlay_update`
[contributing-review-types]: https://github.com/Workiva/over_react_codemod/blob/master/CONTR …

CPLAT-6563 Codemod to migrate consumer overlays to new APIs, fixing deprecations

---

CHANGELOG.md
lib/src/constants.dart
lib/src/creator_utils.dart
lib/src/executables/component2_upgrade.dart
lib/src/executables/react16_dependency_override_update.dart
lib/src/executables/react16_upgrade.dart
lib/src/react16_suggestors/dependency_override_updater.dart
pubspec.yaml
test/react16_suggestors/dependency_override_updater_test.dart

This release updates the React 16 / Component2 executables to utilize the `Ignorable` class - ensuring that consumers can utilize a comment like so to fend off edge cases in which the codemod should not apply a patch.
```dart
// orcm_ignore
```
FYA: @greglittlefield-wf @joebingham-wk @kealjones-wk @sydneyjodon-wk

RM-58005 Release over_react_codemod 1.3.2 (CPLAT-7563 comment escape hatch)

---

lib/src/component2_suggestors/component2_constants.dart
lib/src/component2_suggestors/component2_utilities.dart
lib/src/component2_suggestors/componentwillmount_migrator.dart
test/component2_suggestors/class_name_and_annotation_migrator_test.dart
test/component2_suggestors/component2_utilities_test.dart
test/component2_suggestors/componentdidupdate_migrator_test.dart
test/component2_suggestors/componentwillmount_migrator_test.dart
test/component2_suggestors/copyunconsumeddomprops_migrator_test.dart
test/component2_suggestors/setState_updater_test.dart

Part of [CPLAT-5212](https://jira.atl.workiva.net/browse/CPLAT-5212) was to add a suggestor that takes `componentWillMount` and transitions it to `init`. 
We need to modify that to go from `componentWillMount` to `componentDidMount`.
- Update the `componentWillMount` suggestor with the following changes:
- If there is also a `componentDidMount` in that component
- Move the body of `componentWillMount` to the beginning of componentDidMount
- Copy any annotations not already present to `componentDidMount` (e.g., `@mustCallSuper`)
- Remove componentWillMount.
- If the `componentWillMount` had a super-call, change it to `componentDidMount`
- UNLESS there's already a super-call in the existing `componentDidMount`
- If there is **not** a `componentDidMount` in that component
- Rename …

CPLAT-7175 Update componentWillMount Suggestor

---

lib/src/dart2_suggestors/pubspec_over_react_upgrader.dart
lib/src/executables/react16_dependency_override_update.dart
lib/src/executables/react16_upgrade.dart
lib/src/react16_suggestors/constants.dart
lib/src/react16_suggestors/pubspec_react_upgrader.dart
test/react16_suggestors/pubspec_react_updater_test.dart

1. We modify all top-level renders to have a root of `ErrorBoundary` - but we are not forcing the addition of the `over_react` dependency.
2. We need consumers to pull in the alpha release of `web_skin_dart` for testing purposes - which means we need these alpha releases of `react` / `over_react` to be specified as `dependencies`, not `dependency_overrides` in order to automatically pull in WSD as well for the testing branch.
1. https://github.com/Workiva/over_react_codemod/pull/60/commits/64f312541f6a0f6b9795a1377c4588719bc9f635
2. https://github.com/Workiva/over_react_codemod/pull/60/commits/34a1d45bdc6845fd06dc34efdcfa0858a6570daa
Update React 16 codemod dependency update logic
_[See CONTRIBUTING.md][contributing-review-types] for more details on review types (+1 / QA +1 / +10) and …

React 16 testing dependency logic update

---

CHANGELOG.md
pubspec.yaml

* [CPLAT-7863: Update logic to not rely on imports and allows over_react import](https://github.com/Workiva/over_react_codemod/pull/63)
* [Just cleanup some unused import lints](https://github.com/Workiva/over_react_codemod/pull/64)
Requested by: @kealjones-wk
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_codemod/compare/1.4.0...Workiva:release_over_react_codemod_1.4.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react_codemod/compare/1.4.0...1.4.1

RM-59076 Release over_react_codemod 1.4.1

---

CHANGELOG.md
lib/src/executables/react16_upgrade.dart
pubspec.yaml

Revert react16_upgrade change in 1.4.0 that forced `over_react` to be added whenever just `react` was listed as a dependency.
This changed was causing consumers' builds to fail unless they added the `over_react` dependency, which isn't desirable for every package.
@aaronlademann-wf @kealjones-wk @joebingham-wk

RM-59972 Release over_react_codemod 1.4.3 (hotfix)

---

lib/src/creator_utils.dart
lib/src/dart2_suggestors/pubspec_over_react_upgrader.dart
lib/src/react16_suggestors/pubspec_react_upgrader.dart
lib/src/util.dart
test/dart2_suggestors/pubspec_over_react_upgrader_test.dart
test/react16_suggestors/pubspec_react_updater_test.dart
test/util_test.dart

The react16_post_rollout_cleanup updates react/over_react version ranges, but it's output always uses the greater-than/less-than syntax instead of the caret syntax, which is less than ideal, and will likely result in someone updating it manually at some point.
While not essential would be nice to just use carets from the get-go.
Current behavior when running `react16_post_rollout_cleanup`:
```diff
-  over_react: ">=2.5.0 <4.0.0"
-  react: ">=4.7.0 <6.0.0"
+  over_react: ">=3.1.0 <4.0.0"
+  react: ">=5.1.0 <6.0.0"
```
Check to see if the new version constraint can be represented with the caret syntax, and use it when it can.
New behavior when running `react16_post_rollout_cleanup`:
```diff
-  over_react: ">=2.5.0 <4.0.0"
-  react: ">=4.7.0 <6.0.0"
+  over_react: ^3.1.0
+  react: ^5.1.0
``` …

CPLAT-8187 Use caret deps when possible in version range updates

---

lib/src/executables/react16_post_rollout_cleanup.dart
pubspec.yaml

This patch release changes the over_react version for the `react16_post_rollout_cleanup` codemod from `^3.1.0` to `^3.1.3`.
---
@greglittlefield-wf @kealjones-wk @joebingham-wk

RM-61324 Release over_react_codemod 1.5.1

---

lib/src/boilerplate_suggestors/advanced_props_and_state_class_migrator.dart
lib/src/boilerplate_suggestors/boilerplate_utilities.dart
lib/src/boilerplate_suggestors/props_meta_migrator.dart
lib/src/boilerplate_suggestors/simple_props_and_state_class_migrator.dart
lib/src/boilerplate_suggestors/stubbed_props_and_state_class_remover.dart
lib/src/dart2_suggestors/props_and_state_companion_class_remover.dart
lib/src/executables/boilerplate_upgrade.dart
test/boilerplate_suggestors/props_meta_migrator_test.dart
test/boilerplate_suggestors/simple_props_and_state_class_migrator_test.dart
test/boilerplate_suggestors/stubbed_props_and_state_class_remover_test.dart
test/dart2_suggestors/props_and_state_companion_class_remover.suggestor_test

Need to remove props / state "companion" classes as part of the boilerplate update codemod.
Use the suggestor that was already written as part of the dart2 codemod.
Please review: @greglittlefield-wf @joebingham-wk @sydneyjodon-wk 

CPLAT-9409 Remove props/state “companion” classes as part of the boilerplate update

---

Dockerfile
lib/src/boilerplate_suggestors/boilerplate_utilities.dart
lib/src/boilerplate_suggestors/props_meta_migrator.dart
lib/src/boilerplate_suggestors/props_mixins_migrator.dart
lib/src/boilerplate_suggestors/simple_props_and_state_class_migrator.dart
lib/src/util.dart
pubspec.yaml
test/boilerplate_suggestors/props_mixin_migrator_test.dart

We need a migrator that converts standalone `@PropsMixin()` / `@StateMixin` classes into mixins, and removes / deprecates the `meta` / `props` / `state` fields/getters in the class.
1. Add logic for the migrator
2. Write tests
Please review: @joebingham-wk @sydneyjodon-wk @greglittlefield-wf 

CPLAT-9411 Add standalone PropsMixin / StateMixin migrator

---

lib/src/boilerplate_suggestors/advanced_props_and_state_class_migrator.dart
lib/src/boilerplate_suggestors/annotations_remover.dart
lib/src/boilerplate_suggestors/boilerplate_utilities.dart
lib/src/boilerplate_suggestors/props_meta_migrator.dart
lib/src/boilerplate_suggestors/props_mixins_migrator.dart
lib/src/boilerplate_suggestors/simple_props_and_state_class_migrator.dart
lib/src/executables/boilerplate_upgrade.dart
test/boilerplate_suggestors/props_meta_migrator_test.dart
test/boilerplate_suggestors/props_mixin_migrator_test.dart
test/boilerplate_suggestors/simple_props_and_state_class_migrator_test.dart

We want to change the global variable being used to keep track of props / state classes that have been converted to the new boilerplate by sibling migrators to a variable within an object that can be passed around by utilities / migrators that need it.
In doing so, we'll
* eliminate the risk of different areas of the code unintentionally interfering with each other's data (including in tests like this)
* make it easier to reason about where the data is used
* decouple code that reads/writes to this map from the consuming code
* Create a `ClassToMixinConverter` class, which contains a `convertedClassNames` getter to access the private `_convertedClassNames` field.
* Create a single instance of this class within `main()` of `boilerplate_upgrade.dart`, and pass the instance around to the …

Use utility class to contain map of converted classNames

---

lib/src/boilerplate_suggestors/advanced_props_and_state_class_migrator.dart
lib/src/boilerplate_suggestors/annotations_remover.dart
lib/src/boilerplate_suggestors/boilerplate_utilities.dart
lib/src/boilerplate_suggestors/migration_decision.dart
lib/src/boilerplate_suggestors/props_meta_migrator.dart
lib/src/boilerplate_suggestors/props_mixins_migrator.dart
lib/src/boilerplate_suggestors/simple_props_and_state_class_migrator.dart
lib/src/boilerplate_suggestors/stubbed_props_and_state_class_remover.dart
lib/src/dart2_suggestors/props_and_state_companion_class_remover.dart
lib/src/executables/boilerplate_upgrade.dart
lib/src/react16_suggestors/react16_utilities.dart
lib/src/util.dart
test/boilerplate_suggestors/advanced_props_and_state_class_migrator_test.dart
test/boilerplate_suggestors/annotations_remover_test.dart
test/boilerplate_suggestors/props_meta_migrator_test.dart
test/boilerplate_suggestors/props_mixin_migrator_test.dart
test/boilerplate_suggestors/simple_props_and_state_class_migrator_test.dart
test/boilerplate_suggestors/stubbed_props_and_state_class_remover_test.dart
test/util.dart

> **NOTE:** I'd recommend just reading through the `advanced_props_and_state_migrator_test.dart` file without attempting to make sense of the diff.
Currently, when the codemod runs the `AdvancedPropsAndStateClassMigrator`, the migrator does not short-circuit if a custom superclass, or one or more mixins is not present in the map of "known converted classes" that the migrators update as classes are converted.
This is done because we have no way to control the order in which classes are visited by the suggestor.  This means that just because a superclass or mixin is not present in the map of "known converted classes" at the time the subclass is visited - does not mean it will never be converted.
We also need to improve how we communicate to the consumer when our codemod short-circuits …

CPLAT-9677 Improve class migration short-circuit logic + consumer communication

---

lib/src/boilerplate_suggestors/boilerplate_utilities.dart
lib/src/boilerplate_suggestors/migration_decision.dart
test/boilerplate_suggestors/advanced_props_and_state_class_migrator_test.dart
test/boilerplate_suggestors/simple_props_and_state_class_migrator_test.dart
test/executables/react16_ci_precheck_test.dart
test/executables/react16_upgrade_test.dart

Found a couple of things while QA'ing #80 that weren't worth preventing it from merging, but deserve to be cleaned up before finalizing the codemod / merging the integration branch into master.
Improve the accuracy and clarity of some FIXME comments that are generated by the codemod(s).
Please review: @joebingham-wk 

Final cleanup for new boilerplate codemod

---

lib/src/boilerplate_suggestors/constants.dart
lib/src/executables/boilerplate_upgrade.dart
pubspec.yaml

The migration to the new over_react boilerplate will require updated lower bounds for the `react` and `over_react` dependencies for consumer libs.
Add a standalone interactive codemod that runs before the rest of the migrators that updates the react / over_react dependencies.
> _NOTE: These versions don't exist yet, but they should / will very soon._ 
Please review: @greglittlefield-wf @sydneyjodon-wk @joebingham-wk  …

CPLAT-10066 Update react / over_react versions for boilerplate migration

---

lib/src/executables/boilerplate_upgrade.dart

As part of the new boilerplate upgrade, the following ignores should be removed:
```diff
- // ignore: uri_has_not_been_generated
part 'foo.over_react.g.dart';
```
`GeneratedPartDirectiveIgnoreRemover` already does this, so we just need to add it to run in the boilerplate codemod.
- Added existing `GeneratedPartDirectiveIgnoreRemover` to `boilerplate_upgrade`.
@joebingham-wk @greglittlefield-wf @aaronlademann-wf  …

CPLAT-10335 Add GeneratedPartDirectiveIgnoreRemover to Boilerplate Codemod

---

lib/src/boilerplate_suggestors/factory_ignore_comment_mover.dart
lib/src/executables/boilerplate_upgrade.dart
test/boilerplate_suggestors/factory_ignore_comment_mover.suggestor_test
test/suggestors_test.dart

Currently, most factories look like this:
```dart
UiFactory<FooProps> Foo =
// ignore: undefined_identifier
_$Foo;
```
However, we want the comment to go at the end of the line, so it can become:
```dart
UiFactory<FooProps> Foo = _$Foo; // ignore: undefined_identifier
```
- Add suggestor that moves these ignore comments
- Add tests

CPLAT-10380 Add suggestor to move factory ignore comments

---

lib/src/boilerplate_suggestors/advanced_props_and_state_class_migrator.dart
lib/src/boilerplate_suggestors/boilerplate_utilities.dart
test/boilerplate_suggestors/advanced_props_and_state_class_migrator_test.dart

When the boilerplate codemod converts components to the "shorthand" (mixin-only) syntax, there is a case where `consumedProps` behavior is changed: when the original props extends directly from UiProps and mixes in a single mixin.
This is because the default consumed props go from being derived from the concrete props class to being derived from the mixin.
Before codemod:
```dart
@Factory()
UiFactory<FooProps> Foo = _$Foo;
@PropsMixin()
abstract class FooPropsMixin {
Map get props;
String foo;
}
@Props()
class FooProps extends UiProps with FooPropsMixin {}
@Component2()
class FooComponent extends UiComponent2<FooProps> {  
get defaultProps => (newProps()..foo = 'bar');
render() {
print(props);                 // {FooPropsMixin.foo: bar}
print(copyUnconsumedProps()); // {FooPropsMixin.foo: …
```

CPLAT-10164 Preserve consumedProps behavior when shorthand used

---

lib/src/boilerplate_suggestors/advanced_props_and_state_class_migrator.dart
lib/src/boilerplate_suggestors/boilerplate_utilities.dart
lib/src/component2_suggestors/component2_utilities.dart
lib/src/constants.dart
test/boilerplate_suggestors/advanced_props_and_state_class_migrator_test.dart
test/util.dart

Since over_react's new boilerplate will be consuming all mixed in props by defaults (via https://github.com/Workiva/over_react/pull/485), we need to update the codemod to preserve the same set of consumed props when converting legacy boilerplate.
**1\. Update migrators to preserve this behavior via `consumedProps` impl updates:**
- simple_props_and_state_migrator - No changes necessary.
These classes will result in only one props mixin being used, so the default behavior change still results in the single mixin being consumed.
- advanced_props_and_state_migrator
Cases:
1. Component already overrides `consumedProps`; do nothing
1. Props class had no members, so no mixin was created: add `consumedProps` override that consumes no props
1. Mixin was created from props/state class; add …

CPLAT-10515 Preserve consumed props behavior defaults

---

pubspec.yaml

This release provides a codemod to assist consumers with the migration to the [new "v3" over_react component boilerplate](https://github.com/Workiva/over_react/blob/master/doc/new_boilerplate_migration.md) that was recently released in [over_react 3.5.0](https://github.com/Workiva/over_react/pull/486).
* [CPLAT-9205 Codemod for New Boilerplate](https://github.com/Workiva/over_react_codemod/pull/72)
* [CPLAT-10066 Update react / over_react versions for boilerplate migration](https://github.com/Workiva/over_react_codemod/pull/84)
* [CPLAT-10081 Address some boilerplate codemod edge cases](https://github.com/Workiva/over_react_codemod/pull/85)
* [CPLAT-10164 Preserve consumedProps behavior when shorthand …

RM-61418 Release over_react_codemod 1.6.0

---

docs/boilerplate_upgrade.md

https://github.com/Workiva/over_react_codemod/pull/92 updates FIXME comments to link to more advanced instructions as opposed to including them in consumer repos, to cut down on clutter.
Example of the new comments:
```
// FIXME: `PlaceholderNodeProps` could not be auto-migrated to the new over_react boilerplate because it extends from WsDraggableItemProps, which comes from from an external library.
// Once that component has been upgraded to the new boilerplate, see instructions here: https://github.com/Workiva/over_react_codemod/tree/master/docs/boilerplate_upgrade.md#external-superclass
```
which links to https://github.com/Workiva/over_react_codemod/tree/master/docs/boilerplate_upgrade.md#external-superclass.
That branch isn't ready to be merged yet, but we want to be able to use …

Add upgrade instructions, to be referenced in followup PR

---

lib/src/boilerplate_suggestors/annotations_remover.dart
lib/src/dart2_suggestors/generated_part_directive_ignore_remover.dart
test/boilerplate_suggestors/annotations_remover_test.dart
test/dart2_suggestors/generated_part_directive_ignore_remover.suggestor_test

Newlines would be removed when removing annotations and part ignores, leading to undesirable output even after running dartfmt:
Before:
```dart
import 'foo.dart';
// ignore: uri_has_not_been_generated
part `foo_component.over_react.g.dart`;
/// Displays the foos.
@Factory()
UiFactory Foo = _$Foo; ignore: undefined_identifier
```
After, dartfmt'd:
```dart
import 'foo.dart';
part `foo_component.over_react.g.dart`;
/// Displays the foos.
UiFactory Foo = _$Foo; ignore: undefined_identifier
```
Desired output:
```dart
import 'foo.dart';
part `foo_component.over_react.g.dart`;
/// Displays the foos.
UiFactory Foo = _$Foo; ignore: undefined_identifier
```
- Improve newline handling when removing part ignores
- Improve newline handling when removing annotations
- Add tests
Improve handling of …

CPLAT-11169 Improve handling of newlines in boilerplate upgrades

---

.travis.yml
docs/boilerplate_upgrade.md
lib/src/creator_utils.dart
lib/src/executables/boilerplate_upgrade.dart
lib/src/executables/component2_upgrade.dart
lib/src/executables/dart2_upgrade.dart
lib/src/executables/react16_ci_precheck.dart
lib/src/executables/react16_consumer_overlay_update.dart
lib/src/executables/react16_dependency_override_update.dart
lib/src/executables/react16_post_rollout_cleanup.dart
lib/src/executables/react16_upgrade.dart
lib/src/react16_suggestors/react16_utilities.dart
lib/src/util.dart
pubspec.yaml

We direct consumers to re-run the boilerplate_upgrade script after making certain changes to individual components. However, there is no way for them to run the script on one or some files, only all files. Running the script on all files can lead to many changes in files other than the ones the consumer updated, which may cause him or her to abandon ship on the update entirely (✋ )
This PR adds the ability to specify one or more paths or globs to the boilerplate_upgrade codemod to run the codemod only on the specified files.
- Add ability to pass paths or globs to boilerplate_upgrade as basic args to only run the codemod on the specified files.
Please review: …

CPLAT-11695 Add option to specify a path or glob upon which to run boilerplate upgrade codemod

---

CHANGELOG.md
pubspec.yaml

* [CPLAT-10914 Fix issues discovered during initial boilerplate rollout](https://github.com/Workiva/over_react_codemod/pull/92)
* [Add upgrade instructions, to be referenced in followup PR](https://github.com/Workiva/over_react_codemod/pull/93)
* [CPLAT-11169 Improve handling of newlines in boilerplate upgrades](https://github.com/Workiva/over_react_codemod/pull/94)
* [Add additional paths forward for components requiring breaking changes before upgrading](https://github.com/Workiva/over_react_codemod/pull/95)
* [CPLAT-11695 Add option to specify a path or glob upon which to run boilerplate upgrade codemod](https://github.com/Workiva/over_react_codemod/pull/97)
Requested by: @smaifullerton-wk
Diff Between Last Tag and Proposed Release: …

RM-72268 Release over_react_codemod 1.7.0

---

CHANGELOG.md
pubspec.yaml

* [More tweaks/improvements to boilerplate codemod](https://github.com/Workiva/over_react_codemod/pull/96)
Requested by: @greglittlefield-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_codemod/compare/1.7.0...Workiva:release_over_react_codemod_1.8.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react_codemod/compare/1.7.0...1.8.0

RM-81673 Release over_react_codemod 1.8.0

---

bin/react17_dependency_override_update.dart
bin/react17_upgrade.dart
lib/src/executables/react17_dependency_override_update.dart
lib/src/executables/react17_upgrade.dart
pubspec.yaml

For the sourcegraph campaign, we need two different codemod scripts that:
1. Widen current versions to accept react-dart 6.0.0 and over_react 4.0.0
2. Add overrides for testing the alpha versions
- Added `react17_upgrade` and `react17_dependency_override_update` codemod executables 

CPLAT-12873 Create executables to update pubspec for React 17 Rollout

---

CHANGELOG.md
pubspec.yaml

* [CPLAT-12873 Create executables to update pubspec for React 17 Rollout](https://github.com/Workiva/over_react_codemod/pull/102)
Requested by: @sydneyjodon-wk
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_codemod/compare/1.9.0...Workiva:release_over_react_codemod_1.10.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react_codemod/compare/1.9.0...1.10.0
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6153708125028352/?pull_number=103&repo_name=Workiva%2Fover_react_codem …

RM-86042 Release over_react_codemod 1.10.0

---

lib/src/creator_utils.dart
lib/src/executables/react17_dependency_override_update.dart
lib/src/react16_suggestors/dependency_override_updater.dart
test/react16_suggestors/dependency_override_updater_test.dart

We need the React 17 test executable to add dependency_overrides instead of setting the dependency to a specific version.
- Refactor `DependencyOverrideUpdater` to be able to add git dependency overrides
- Add `DependencyCreator.fromOverrideConfig` to `DependencyCreator`
- Refactor / add tests
- Change the functionality of `react17_dependency_override_update` to add dependency overrides
- react
- url: `https://github.com/cleandart/react-dart.git`
- ref: `6.0.0-wip`
- over_react
- url: `https://github.com/Workiva/over_react.git`
- ref: `release_over_react_4.0.0`
While we perform many automated checks before auto-merging, some manual checks are …

CPLAT-12873 Switch React 17 Test Executable to Add Overrides

---

CHANGELOG.md
pubspec.yaml

* [CPLAT-12873 Switch React 17 Test Executable to Add Overrides](https://github.com/Workiva/over_react_codemod/pull/104)
Requested by: @joebingham-wk
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_codemod/compare/1.10.0...Workiva:release_over_react_codemod_1.11.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react_codemod/compare/1.10.0...1.11.0
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6153708125028352/?pull_number=105&repo_name=Workiva%2Fover_react_codemod)

RM-90277 Release over_react_codemod 1.11.0

---

CHANGELOG.md
pubspec.yaml

* [CPLAT-12621 Codemod to update factory syntax for Dart 2.9](https://github.com/Workiva/over_react_codemod/pull/106)
* [CPLAT-13196 Add Flag For Core Check](https://github.com/Workiva/over_react_codemod/pull/109)
Requested by: @joebingham-wk
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_codemod/compare/1.11.0...Workiva:release_over_react_codemod_1.12.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react_codemod/compare/1.11.0...1.12.0
This pull request can be recreated by clicking …

RM-90664 Release over_react_codemod 1.12.0

---

pubspec.yaml

* [Remove deprecated authors field from pubspec.yaml](https://github.com/Workiva/over_react_codemod/pull/112)
* [Widen Dependency Ranges Blocking Dart 2.13](https://github.com/Workiva/over_react_codemod/pull/114)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_codemod/compare/1.12.0...Workiva:release_over_react_codemod_1.12.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react_codemod/compare/1.12.0...1.12.1
This pull request can be recreated by clicking …

RM-94084 Release over_react_codemod 1.12.1

---

lib/src/util/component_usage.dart
test/util/component_usage_migrator_test.dart
test/util/component_usage_test.dart

There are some usages of built_value's `Built.toBuilder` method that cause issues detected as component usages.
Take, for example, the expression in the following function:
```dart
void example(Built b) {
b.toBuilder();
}
```
When the `toBuilder` usages are resolved, the `getComponentUsage` is usually able to use the static type information available to determine that they're not OverReact component usages, since the result of the `toBuilder()` call isn't a subtype of `UiProps`, so `getComponentUsage` returns `null`.
However, if toBuilder is called on a `dynamic` object, such as in this example:
```dart
void example(dynamic b) {
b.toBuilder();
}
```
then `getComponentUsage` doesn't have any static information on what type `toBuilder` returns (similar to if this call wasn't fully resolved …

CPLAT-16174 Fix dynamic calls involving toBuilder() being detected as unresolved usages

---

Dockerfile
docs/boilerplate_upgrade.md
test/dependency_validator/ignore_updaters/v2_updater_test.dart

This Sourcegraph batch replaces deprecated commands from the Dart SDK with the new ones.
All new CLI commands now live under the main `dart` executable. See this issue for the details
https://github.com/dart-lang/sdk/issues/46100
This PR might need to be checked or tweaked for possible errors in the arguments to 
`dart analyze` and `dart format` since they take slightly different arguments than the original.
In most cases for analyze all the arguments can be removed and it can just be `dart analyze`.
Some of the argument changes were difficult to match and replace in an automated way. Since
there are only a few places that might break, it'll be easier to let the batch create the PR
and then manually adjust them.
`-w` should be removed automatically since overwriting files is now the …

Replace deprecated commands with new dart commands

---

skynet.yaml

This batch changes references to the archived support-client-plat slack channel to now reference the support-ui-platform channel.
`replace "#support-client-plat" "#support-ui-platform"`
CI passing should be sufficient as these changes are documentation changes.
[_Created by Sourcegraph batch change `Workiva/update_slack_channel_fed`._](https://sourcegraph.plat.workiva.net/organizations/Workiva/batch-changes/update_slack_channel_fed)

Update references to the archived slack room #support-client-plat

---

lib/src/constants.dart
lib/src/executables/intl_message_migration.dart

The command line tools break on Windows machines due to hardcoded `/` in file paths.
Use `Platform.pathSeparator` in place of `/` so it works on Windows, which uses `\`
- *[link to the breaking change in the diff]*
- Clone this repo and checkout the `slash-fixes` branch
- In the root of this project globally activate your local copy `dart pub global activate --source path .`
- Try running the command that this tool provides in the root of the a repo to run the intl codemod
- `dart pub global run over_react_codemod:intl_message_migration --yes-to-all`

Use platform separator for paths

---

lib/src/constants.dart
lib/src/executables/intl_message_migration.dart

This crashes on Windows constructing a path of the form /c:usersmissingpathseparators/.
The problem was passing a path to glob of the from <slash>c:<slash>etc. I think the leading slash may have been causing it to be interpreted as a non-Windows path, even though it would have been platform-specific.  But I just converted everything to use package:path rather than using our own split/join logic. Also cleaned up a couple of bits of iterable usage to use literals, and added a toList in another place to avoid possible repeated evaluations. …

Fix intl_message_migration issue with Windows 

---

lib/src/executables/intl_message_migration.dart

Glob wants some weird syntax for absolute Windows paths ('c:/blah/') which is annoying to create. We're not gaining a lot from using it, so just query the Directory object directly.

INTL-67: Avoid using Glob with absolute packageRoots, problematic on Windows

---

lib/src/executables/intl_message_migration.dart

The codemod expects there to be a lib/src directory off of any folder in the given repo with a pubspec.yaml file, which is not always true. The Glob class does not handle filepaths that don't exist (at least until the newer version of Dart that we aren't using yet). This should be resolved.
Adds a try-catch to ignore when the lib directory doesn't exist
Fix bug

INTL-71 Handle lib filepath exception

---

lib/src/intl_suggestors/utils.dart
test/intl_suggestors/utils_test.dart

Remove file line sorting and conditionally add quotes based on multiline status.
* Removed intl file line sorting. This was "shuffling" multiline strings.
* Conditionally add `'` or `'''` to the beginning and end of strings based on multiline status.

INTL-68 Fix multiline string issue

---

lib/src/intl_suggestors/utils.dart
test/intl_suggestors/intl_migrator_test.dart
test/intl_suggestors/utils_test.dart

When we generate message functions, the variables may or may not be delimited by the characters around them. So it could be   '$var', but it could be '$varStuffThatIsNotVariable', in which case we fail to compile. To avoid this, always surround variables with curly braces in the generated interpolations.

INTL-116: Always use {} around variable names in the generated code

---

lib/src/executables/intl_message_migration.dart
lib/src/intl_suggestors/utils.dart
test/executables/intl_message_migration_test.dart
test/intl_suggestors/intl_configs_migrator_test.dart
test/intl_suggestors/intl_migrator_test.dart
test/intl_suggestors/utils_test.dart

I noticed that we never actually removed (or fixed) the sorting by line of output messages, which was a problem for multiline strings. None of our tests actually exercised as far as writing the output file, where this happens.
Add a functional test, modeled after the mui migration test that actually runs the executable and verifies the output files. Very basic so far. …

INTL-117: Add a functional test for intl_message_migration

---

lib/src/intl_suggestors/intl_migrator.dart

It turns out that even if the `hideLabel` attribute is true on `FormComponentDisplayPropsMixin`, we should
still internationalize the string, because it can be visible to screen readers. This will be superseded by Aria labels,
but if it's still in the code we should still be localizing it.
Comments out the code for removing that. I didn't delete it, because it might be useful as an example of how to flag things 
if we have other attributes that are a problem.
[contributing-review-types]: https://github.com/Workiva/over_react_codemod/blob/master/CONTRIBUTING.m …

INTL-114: Comment out the code for adding a FIXME on the label attribute

---

lib/src/executables/intl_message_migration.dart
lib/src/intl_suggestors/intl_migrator.dart
test/executables/intl_message_migration_test.dart
test/intl_suggestors/constant_migrator_test.dart
test/intl_suggestors/intl_migrator_test.dart

There are lots of 
String const cancel => 'Cancel';
that are likely user-visible. Look for these, as const strings that start with an upper case level. Exclude the common case of date formats, which may start with doubled upper-case letters, e.g. 'MM/dd/YYYY'

INTL-115: Make the intl_message_migration also look for likely user-visible String constants

---

lib/src/intl_suggestors/intl_migrator.dart
lib/src/intl_suggestors/utils.dart
test/intl_suggestors/intl_migrator_test.dart

The codemod should be able to handle adjacent strings, which are concatenated by dart.
e.g.
'This string is long enough that we split it up into '
'multiple lines, using separate strings instead of a triple-quoted string'.
Also, this adds an extra check to exclude strings that don't have any alphabetic characters from translation, motivated by running across strings like '[]'. …

INTL-128: intl_message_migration should handle adjacent strings, exclude strings with no alphabetics

---

lib/src/intl_suggestors/intl_migrator.dart
lib/src/util/package_util.dart
test/intl_suggestors/intl_migrator_test.dart

When we have a message we can't get a better name for, we call it intlFunction0, intlFunction1, etc. But it turns out it's often (always?) 0, even when this leads to duplicates. It's trying to use the child numbering of the nodes, but I'm suspicious they might have different parents but still fall in the same larger name.
The exact numbering isn't very important, so change this to just use a counter in the suggestor class, so the numbering is globally unique within a codemod run. …

INTL-127: Fix intl_message_migration function numbering

---

lib/src/executables/intl_message_migration.dart
test/executables/intl_message_migration_test.dart

Typically with the intl_message_migration codemod we only want it to process the lib/ directory, so make that the default. Allow putting directory names, not just file names on the command line so we can make it handle other directories if desired. The biggest case for handling sub-directories is a single repo with multiple packages, but we can (and typically do) handle that by running the codemod separately on each sub-package. …

INTL-132: intl_message_migration should only do the lib directory by default, allow specifying others

---

CHANGELOG.md

We should have CHANGELOG entries.

Add CHANGELOG entries for 2.6.0 release

---

CHANGELOG.md
lib/src/intl_suggestors/intl_migrator.dart
lib/src/intl_suggestors/utils.dart
test/intl_suggestors/constant_migrator_test.dart

If we have
`
const String someButtonText = 'Do Something';
`
we currently produce 
`
final String someButtonText = Intl.doSomething;
`
It might be preferable to produce
`
final String someButtonText = Intl.someButtonText;
`
Changes the intl_message_migration to preserve the original String constant name, when --migrate-constants is used.
[contributing-manual-testing]: https://github.com/Workiva/over_react_codemod/blob/master/CONTRIBUTING.md#manu …

INTL-137: intl_message_migration uses the variable name for constant strings

---

CHANGELOG.md
lib/src/executables/intl_message_migration.dart
test/executables/intl_message_migration_test.dart

This is generated code, we don't need no readability lints.
Add a //ignore comment to the top of the file.

INTL-136: Ignore the lint for unnecessary braces in string interpolation in the intl.dart class

---

lib/src/executables/intl_message_migration.dart
lib/src/intl_suggestors/intl_configs_migrator.dart
lib/src/intl_suggestors/intl_messages.dart
lib/src/intl_suggestors/intl_migrator.dart
lib/src/intl_suggestors/utils.dart
test/intl_suggestors/constant_migrator_test.dart
test/intl_suggestors/intl_configs_migrator_test.dart
test/intl_suggestors/intl_migrator_test.dart

Right now the executable and various methods explicitly reference the output file for the Intl methods. It would be better if there was an abstraction there that would parse the existing file and allow modifying it and rewriting it. For example, that would make it easier to sort by methods, rather than by lines (as is done now, and breaks for multi-line strings).
This just extracts out the file access logic, with minimal changes. …

INTL-139: intl_message_migration: Split out explicit file access, step towards running repeatedly

---

CHANGELOG.md
lib/src/executables/intl_message_migration.dart
lib/src/intl_suggestors/intl_migrator.dart
test/executables/intl_message_migration_test.dart
test/intl_suggestors/constant_migrator_test.dart

There is a typecast error with adjacent strings.
If two different constants in different places have the same variable name, we get duplicates. So this falls back to a content-based name if the name already exists.
Fix the type of the argument. This also requires removing the sort by lines, since that fails for adjacent strings on separate lines.
[contributing-manual-testing]: https://github.com/Workiva/over_react_codemod/blob/master/CONTRIBUTIN …

Fixes problem with adjacent string and duplicated constant names

---

lib/src/executables/intl_message_migration.dart
lib/src/intl_suggestors/intl_messages.dart
lib/src/intl_suggestors/utils.dart
test/executables/intl_message_migration_test.dart
test/intl_suggestors/constant_migrator_test.dart
test/intl_suggestors/intl_configs_migrator_test.dart
test/intl_suggestors/intl_migrator_test.dart

Sorting had been disabled, due to its bad effect on multi-line strings. This adds sorting by function and re-enables it.
This relies further on the IntlMessages object, and replaces its direct file manipulation with storing messages and writing the file once at the end. It also cleans up the API for that a little more, removing or renaming file-specific methods. Adds tests for multi-line message strings and adjacent strings on separate lines, and re-enables the sorting test. …

INTL-165: Re-enable sorting of _intl.dart files

---

CHANGELOG.md
lib/src/executables/intl_message_migration.dart

Turn on the --migrate-constants option by default
Turn on the --migrate-constants option by default

Turn on the --migrate-constants option by default

---

lib/src/intl_suggestors/intl_message_syntax.dart
test/intl_suggestors/constant_migrator_test.dart

If the codemod runs into two getters named the same thing, it will add a number to the second one (in this example, it would be dueDate -> 'Due Date' and dueDate1 -> 'Due date'). However, the usage was not reflecting the increment.
The getter generation passes in an explicit name, because it might be using either the variable name or a name derived from the text. But we were using that name unmodified, instead of using it as the seed to check for an incremented name.
[contributing-review-types]: https://github.com/Workiva/over_react_codemod/blob/master/CONTRI …

INTL-188: Fix incrementing the usage number of duplicate getters

---

lib/src/intl_suggestors/intl_message_syntax.dart
lib/src/intl_suggestors/utils.dart
test/intl_suggestors/utils_test.dart

If there's an explicit newline in a single-line string, we need to escape that in the generated _intl.dart class.
However, that's also a bit of a red flag that there's something odd going on.

Handle explicit newlines in strings

---

CHANGELOG.md
lib/src/intl_suggestors/intl_migrator.dart
test/intl_suggestors/constant_migrator_test.dart

We should not internationalize things that are all uppercase. They are most likely constants and not user strings.
Check for that.

Do not internationalize SCREAMING_CAPS constants

---

CHANGELOG.md
lib/src/intl_suggestors/intl_messages.dart
pubspec.yaml
test/executables/intl_message_migration_test.dart
test/intl_suggestors/intl_messages_test.dart

We're adding an Intl wrapper in w_intl. The codemod should generate code that calls that, rather than basic intl.
Changes the import.
Also adds tests that exercise plurals, etc., rather than just messages.

INTL-346: Use the W_intl wrapper class in the codemod

---

CHANGELOG.md
lib/src/executables/intl_message_migration.dart

Sometimes we don't want to migrate props or children of components, maybe we just want to have the _intl.dart file rewritten with a different import, or have the file sorted. This lets us turn off the main migrator.

Add a --migrate-components option

---

CHANGELOG.md
lib/src/executables/intl_message_migration.dart
lib/src/intl_suggestors/intl_messages.dart
lib/src/intl_suggestors/intl_migrator.dart
test/executables/intl_message_migration_test.dart

We can accumulate methods in the _intl.dart file that we're no longer using. This attempts to prune them out.

Add a --[no]-prune-unused flag to remove unused methods from the _intl.dart file

---

lib/src/intl_suggestors/intl_importer.dart
lib/src/intl_suggestors/intl_message_syntax.dart
lib/src/intl_suggestors/utils.dart
lib/src/mui_suggestors/mui_importer.dart
lib/src/mui_suggestors/unused_wsd_import_remover.dart
test/executables/intl_message_migration_test.dart
test/intl_suggestors/intl_messages_test.dart
test/intl_suggestors/intl_migrator_test.dart
test/intl_suggestors/utils_test.dart

The codemod uses the first few words of the literal string to create a selector. But if the first few words are an interpolated variable, then for
'$numHiddenPills additional values not shown'
we get
GraphUiIntl.GraphMultiEdgeInputPrimitiveComponent_numHiddenPills
It would be better if it ignored the variables for this.
Add the condition which check if string starts with interpolated variable so it will remove the interpolated variable from start 
- *[link to the breaking change in the diff]*

INTL-113 : ignore initial variable names in creating selectors

---

lib/src/executables/intl_message_migration.dart
lib/src/executables/mui_migration.dart
lib/src/util/logging.dart
pubspec.yaml

When repos start adding the codemod dryrun check to their CI, we want them to be able to easily see failures and be able to debug issues. So, let's add some better logging with colors.
Create `logging.dart` file in `utill` directory where mention all colors as per `rec.level`

INTL-174 : Add nicer logging to codemod dryrun check

---

lib/src/executables/intl_message_migration.dart
test/executables/intl_message_migration_test.dart

Add a --no-migrate option that just sorts and possibly prunes
It's nice to just sort the _intl.dart file occasionally to reduce merge conflicts/size of diffs. It's an annoying amount of command line options right now to turn off all the migrators, and some of them you can't. So add a general option for that.

INTL-1071 Add a --no-migrate option that just sorts and possibly prunes

---

lib/src/executables/rmui_bundle_update.dart

When creating the codemod change to update consumers to new RMUI ESM bundle we neglected to include the case in which would add a dependency where there previously wasn't. To remedy this we need to add the `shouldAddDependencies` flag.

FED-1237: add shouldAddDependencies

---

lib/src/intl_suggestors/intl_messages.dart
lib/src/intl_suggestors/message_parser.dart
test/intl_suggestors/intl_messages_test.dart

It's easy to get the name: parameter value wrong when editing an _intl.dart file. 
Rewrite any missing or incorrect name parameters when writing the file to use the format we're using 'PackageNameIntl_methodName'

INTL-1237: Fix names when writing the _intl.dart file

---

lib/src/intl_suggestors/intl_message_syntax.dart
lib/src/intl_suggestors/message_parser.dart
lib/src/intl_suggestors/utils.dart
test/intl_suggestors/constant_migrator_test.dart
test/intl_suggestors/intl_migrator_test.dart

The codemod could create duplicate messages for the same string if the original source code used double quotes. This is because the toSource() method in the analyzer included the quotes for a string literal. We would end up comparing "Search" to 'Search', and failing because the quotes aren't the same. We should consistently handle the strings with quotes removed.
Add a utility method that gets the string without quotes in a consistent way, and call it. Add tests, and fix one test that seemed to be expecting the incorrect result. …

INTL-1250: Fix for creating two copies of identical messages when they used double quotes

---

lib/src/executables/rmui_bundle_update.dart
lib/src/rmui_bundle_update_suggestors/constants.dart
lib/src/rmui_bundle_update_suggestors/dart_script_updater.dart
lib/src/rmui_bundle_update_suggestors/html_script_updater.dart
lib/src/rmui_preparation_suggestors/constants.dart
test/rmui_bundle_updater_suggestors/dart_script_updater_test.dart
test/rmui_bundle_updater_suggestors/html_script_updater_test.dart

Update the codemods added in #212 to also update `link` tags to the new bundle as well as add the `crossorigin=""` attribute.
- Update dart and html bundle updater suggestors to also update link tags and add the `crossorigin=""` attribute
- Write tests.
- `dart pub global run over_react_codemod:rmui_bundle_update --yes-to-all` 
- Make sure all link tags are updated to new bundle and with `crossorigin=""` attribute
- Make sure any script tags that weren't updated are updated …

FED-1326 Update script updater codemods to include link tags

---

CHANGELOG.md
pubspec.yaml

* [FED-1326 Update script updater codemods to include link tags](https://github.com/Workiva/over_react_codemod/pull/228)
* [INTL-1312: Remove stable from test matrix, replace with 2.19.6](https://github.com/Workiva/over_react_codemod/pull/231)
Requested by: @sydneyjodon-wk
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_codemod/compare/2.22.0...Workiva:release_over_react_codemod_2.23.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react_codemod/compare/2.22.0...2.23.0
This pull request can be recreated by clicking …

RM-191498 Release over_react_codemod 2.23.0

---

lib/src/intl_suggestors/intl_messages.dart
test/executables/intl_message_migration_test.dart
test/intl_suggestors/intl_messages_test.dart

People aren't always clear on what's happening with the _intl.dart files and try to do normal code things that won't work, or want to apply formatting that won't be preserved. Add a comment at the beginning to try and clarify.
Adds a comment at the top of the generated code.

INTL-1311:Add an explanatory comment on codemod-generated files

---

lib/src/intl_suggestors/constants.dart
lib/src/intl_suggestors/intl_migrator.dart
lib/src/intl_suggestors/utils.dart
test/intl_suggestors/constant_migrator_test.dart
test/intl_suggestors/intl_migrator_test.dart

Ignore comments did not work at all for const strings, because those are done by a separate migrator.
Extract the code for ignore comments, tidy up very slightly, and implement for ConstantStringMigrator. Add tests.

INTL-1294: Implement ignore comments for const strings

---

lib/src/intl_suggestors/message_parser.dart

If you declare something as a field, which people do, then the codemod crashes trying to parse it.
You're not allowed to put fields in there. Or at least we don't want to allow it. But at least make it tell you which declaration was the problem.
Add a print statement and an explicit throw rather than crashing on a cast error without telling you the problem declaration. …

INTL-1363 : Give a better error message when something in the intl file is not a method

---

lib/src/intl_suggestors/intl_migrator.dart
lib/src/intl_suggestors/message_parser.dart
lib/src/intl_suggestors/utils.dart
test/intl_suggestors/intl_migrator_test.dart

Ignore comments of the form 
```
(mui.MenuItem()
..component = Dom.div.elementType
// ignore_statement: intl_message_migration
..value = 'audit-info'
```
don't work because we start looking for the ignore comment ahead of the full expression. Try looking for them ahead of the line as well. We don't want it to trigger on other lines in the sequence of calls, e.g.
```
(mui.MenuItem()
..component = Dom.div.elementType
// ignore_statement: intl_message_migration
..value = 'audit-info'
..title = 'some translateable string'
```
so only look a depth of one token back. That probably won't catch every condition, but it's better than nothing and shouldn't have too many bad cases if it only looks back one.
_[See CONTRIBUTING.md][contributing-review-types] for more details on review types (+1 / QA +1 …

INTL-231: Try checking for ignore lines within components

---

pubspec.yaml

meta 1.10.0 was just released and breaks things
Change the max allowed version to avoid the problem version.

Limit meta to avoid 1.10.0

---

pubspec.yaml

* [Limit meta to avoid 1.10.0](https://github.com/Workiva/over_react_codemod/pull/238)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_codemod/compare/2.25.0...Workiva:release_over_react_codemod_2.26.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react_codemod/compare/2.25.0...2.26.0
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6153708125028352/?repo_name=Workiva%2Fover_react_codemod&pull_number=239)

RM-210649 Release over_react_codemod 2.26.0

---

pubspec.yaml

Summary
---
This is a batch change to apply a dependency range pin to the meta package
in order to avoid a "bad release". That version causes nearly all of our builds to
fail (anything on analyzer < 5).
So restricting the version range to <1.10.0 works around the issue until we
can upgrade to analyzer 5.
For more info, visit `#lang-dart` in Slack.
[_Created by Sourcegraph batch change `Workiva/avoid_meta_1_10_0`._](https://sourcegraph.plat.workiva.net/organizations/Workiva/batch-changes/avoid_meta_1_10_0)

Avoid meta 1.10.0

---

lib/src/intl_suggestors/message_parser.dart
test/intl_suggestors/intl_messages_test.dart

The intl_suggestors are hard-coded to expect arrow functions, and crash with a parse error if you add one by hand and then try to run the codemod. This is sub-optimal. And pretty easy to fix. One place assumes you can split a string on the '=>' substring, and another place assumes AST structure, but can be easily adapted.
This is analogous to INTL-1589
Fixes, as above. …

INTL-1591: Handle non-arrow intl functions

---

lib/src/intl_suggestors/utils.dart
test/intl_suggestors/constant_migrator_test.dart

Ignore comments were not being seen if they followed a regular comment. e.g.
// Platform keys:
// ignore_statement: intl_message_migration
const winPlatformKey = 'Win';
The reason is that when ask for precedingComments we get the first one if there are several.
Go through looking for all comments.

INTL-1626: Multi line ignore comments

---

lib/src/intl_suggestors/intl_migrator.dart
lib/src/intl_suggestors/utils.dart
test/intl_suggestors/constant_migrator_test.dart
test/intl_suggestors/intl_migrator_test.dart
test/intl_suggestors/utils_test.dart

Exclude Pendo IDs, or similar from conversion. Those are of the form Period.Separated.Uppercase.Words
- It turns out that our existing check for CamelCaseWords wasn't actually working. Or at least it was checking for quoted strings, meaning e.g. var foo = "'stuff'". Which are extremely rare. I didn't think this made any sense at all, so I just dropped the "quoted" requirement and allowed periods within the word. It also had no tests, so it's hard to know what the intent was. Added some tests.
- We also weren't using the checks for strings to exclude in the constant string migrator, so I started including them.
- We used strings that we expected to be converted in test cases, which met the camel case requirement (if we didn't have quotes), specifically 'testString1', 'testString2'. I …

INTL-1677: Exclude Pendo ID pattern in codemod

---

lib/src/executables/intl_message_migration.dart

When engineers see a CI check failure, they are not provided any indication of next steps.
> 1 change(s) needed.
- modified failure message to include instructions on how to run the INTLcodemod locally
modify failure message to include instructions on how to run the INTL codemod locally

INTL-1685: improve failure message

---

lib/src/util/package_util.dart

Newer versions of Dart don't support the `pub` executable on its own, it must be run via `dart pub`.
Update code that runs `pub get` subprocesses to run `dart pub get` instead.

Update `pub get` commands to `dart pub get`

---

pubspec.yaml

* [INTL-1685: improve failure message](https://github.com/Workiva/over_react_codemod/pull/259)
* [Update `pub get` commands to `dart pub get`](https://github.com/Workiva/over_react_codemod/pull/261)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_codemod/compare/2.28.0...Workiva:release_over_react_codemod_2.29.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react_codemod/compare/2.28.0...2.29.0
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6 …

RM-220065 Release over_react_codemod 2.29.0

---

lib/src/intl_suggestors/intl_importer.dart
test/executables/intl_message_migration_test.dart
test/intl_suggestors/intl_importer_test.dart

- Add the ability for the codemod to decide how the intl class import statement will be formatted, ie. package format vs. relative format. It should behave something like this:
- If the file has only **package** imports, go with a **package** format
- If the file has only **relative** imports, go with a **relative** format
- If the file has a mix of both, go with the **package** format
- If the file has no imports, go with the **package** format
- Determine where to insert the import statement. The `_insertionLocationForPackageImport` function is responsible for this.
- This function inspects the existing import directives in the file and calculates the appropriate insertion point for the `intl` import. 
- Tracked whether the file has **package** or **relative** imports by iterating …

INTL-1332: Add import smarts to codemod

---

test/test_fixtures/over_react_project/pubspec.yaml
test/test_fixtures/rmui_project/pubspec.yaml
test/test_fixtures/wsd_project/pubspec.yaml

This PR widens the allowable version ranges to over_react 5.0.0 / over_react_test 3.0.0 so that all repos at Workiva can consume without updating all repositories in lock step.
These major versions are a critical step towards unlocking null safety in Workiva's Dart ecosystem - and **have already been tested and verified as safe for consumption** using the `over_react_codemod` test PR [listed in this SourceGraph batch](https://sourcegraph.plat.workiva.net/organizations/Workiva/batch-changes/over_react_5_test).
Due to the exhaustive consumption testing already performed in this repository by the FED team prior to releasing over_react 5.0.0, **these changes can be merged without approval from a FED team member.**
---
For more information about these changes, see [this …

Allow consumption of null-safe over_react and over_react_test versions

---

test/test_fixtures/over_react_project/pubspec.yaml
test/test_fixtures/rmui_project/pubspec.yaml
test/test_fixtures/wsd_project/pubspec.yaml

This PR sets the lower bound of over_react to `^5.0.0` and over_react_test to `^3.0.0` so that all repos at Workiva 
are consuming the null-safe versions of these packages.
These major versions are a critical step towards unlocking null safety in Workiva's Dart ecosystem - 
and **have already been tested and verified as safe for consumption** using the 
`over_react_codemod` test PR [listed in this SourceGraph batch](https://sourcegraph.plat.workiva.net/organizations/Workiva/batch-changes/over_react_5_test).
Due to the exhaustive consumption testing already performed in this repository by the FED team prior to 
releasing over_react 5.0.0, **these changes can be merged without approval from a FED team member.**
For more information about these changes, see [this …

Consume null-safe over_react v5 and over_react_test v3

---

pubspec.yaml

* [FED-1979 Add suggestor to replace null argument in dom callback](https://github.com/Workiva/over_react_codemod/pull/272)
* [FED-2094 Add suggestor that replaces useRef with useRefInit](https://github.com/Workiva/over_react_codemod/pull/273)
* [FED-1718 Callback ref null safety hint suggestor](https://github.com/Workiva/over_react_codemod/pull/275)
* [Allow consumption of null-safe over_react and over_react_test versions](https://github.com/Workiva/over_react_codemod/pull/277)
* [Consume null-safe over_react v5 and over_react_test v3](https://github.com/Workiva/over_react_codemod/pull/279)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_codemod/compare/2.30.0...Workiva:re …

RM-232877 Release over_react_codemod 2.31.0

---

pubspec.yaml

* [FEDX-690 : GHA OSS changes](https://github.com/Workiva/over_react_codemod/pull/283)
* [FED-1721 Null safety preparation for class component default props / initial state](https://github.com/Workiva/over_react_codemod/pull/284)
* [FED-2444 Null safety preparation for conditional prop function calls](https://github.com/Workiva/over_react_codemod/pull/285)
* [FED-2610 Synchronize with over_react impl; pull in AbstractProps fix](https://github.com/Workiva/over_react_codemod/pull/286)
* [INTL-1793 : Have over_react_codemod show deprecation message](https://github.com/Workiva/over_react_codemod/pull/288)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_codemod/compare/2.31.0... …

RM-252172 Release over_react_codemod 2.32.0

---

pubspec.yaml

In order to help with build times and ease null safety migration, we've opted to replace mockito with mocktail. This batch runs the codemod to swap things out, but may require manual intervention.
FEDX will come around and fix things up unless you beat us to it. Once CI is green and the PR is not in draft, you can review and merge it.
[_Created by Sourcegraph batch change `Workiva/mocktail`._](https://workiva.sourcegraphcloud.com/organizations/Workiva/batch-changes/mocktail)

Replace mockito with mocktail

---

.github/workflows/dart_ci.yml
dart_dependency_validator.yaml
pubspec.yaml

While putting up another PR, I noticed a couple issues:
1. The SBOM step failing ([example](https://github.com/Workiva/over_react_codemod/actions/runs/10189096191/job/28186489940)) on one of the matrix runs; it looks like it doesn't like being run more than once
2. dependency_validator failing on imports within test fixture packages
These seemed worth PRing to master separately.
1. Update SBOM step to only run once
2. Update / clean up dependency_validator config
- Upgrade to [dependency_validator 4.0.0](https://github.com/Workiva/dependency_validator/blob/master/CHANGELOG.md#400), which doesn't have false positives for `package:` imports in comments and strings!
- Add exclude to files within test_fixtures directory
- Clean up `ignore`s in config no longer needed with 4.0.0 and new …

FED-3006 CI fixes and dependency_validator cleanup

---

README.md

The README referenced a codemod that had been removed, and didn't describe a path forward.
Update README to show how to run that codemod.

FED-1855 Update instructions for dart2_upgrade codemod

---

CHANGELOG.md
pubspec.yaml

* [FED-1855 Update instructions for dart2_upgrade codemod](https://github.com/Workiva/over_react_codemod/pull/263)
* [Replace mockito with mocktail](https://github.com/Workiva/over_react_codemod/pull/287)
* [FED-1885: Prop requiredness codemod](https://github.com/Workiva/over_react_codemod/pull/290)
* [FED-3006 CI fixes and dependency_validator cleanup](https://github.com/Workiva/over_react_codemod/pull/291)
Requested by: @greglittlefield-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_codemod/compare/2.32.0...Workiva:release_over_react_codemod_2.33.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react_codemod/compare/2.32.0...2.33.0
The logs for the request that created this PR …

RM-260254 Release over_react_codemod 2.33.0

---

lib/src/dart3_suggestors/null_safety_prep/use_ref_init_migration.dart
test/dart3_suggestors/null_safety_prep/use_ref_init_migration_test.dart

The null_safety_prep codemod updates cases like `useRef<Element>(null)` to `useRefInit<Element>(null)`, which, while not incorrect and won't cause issues during migrations, isn't ideal.
- Handle the explicit `null` value
- Add tests
- CI passes

FED-3209 Remove explicit null passed to useRef

---

lib/src/dart3_suggestors/null_safety_prep/class_component_required_default_props.dart
lib/src/dart3_suggestors/null_safety_prep/utils/class_component_required_fields.dart
lib/src/dart3_suggestors/required_props/bin/codemod.dart
lib/src/dart3_suggestors/required_props/codemod/recommender.dart
lib/src/executables/null_safety_migrator_companion.dart
test/executables/required_props_collect_and_codemod_test.dart
test/test_fixtures/required_props/test_package/lib/entrypoint.dart
test/test_fixtures/required_props/test_package/lib/src/test_class_component_defaults.dart

Right now, the class component codemod always makes defaulted props required, but that goes against our guidance (see [here](https://github.com/Workiva/over_react/blob/master/doc/null_safety/null_safe_migration.md#prop-nullability)) in cases where those props are public.
This codemod should only make those props required when classes are private.
- Move class defaulted props codemod into prop requiredness codemod to use public api info to only make defaulted props required if they are not public …

FED-2994 Update class component defaults codemod to take public-ness into account

---

test/test_fixtures/rmui_project/pubspec.yaml

This PR raises the min version of react_material_ui to 1.214.2. Passing CI
For more info, reach out to `#support-uip` on Slack.
[_Created by Sourcegraph batch change `Workiva/react_material_ui_raise_min_v1_214_2`._](https://workiva.sourcegraphcloud.com/organizations/Workiva/batch-changes/react_material_ui_raise_min_v1_214_2)

Raise the react_material_ui dependency min to v1.214.2

---

pubspec.yaml

This PR raises unpins the meta dependency to allow the latest.
Passing CI should be sufficient for QA, so feel free to review and merge this once CI completes.
[_Created by Sourcegraph batch change `Workiva/meta_raise_min_v1_16_0`._](https://workiva.sourcegraphcloud.com/organizations/Workiva/batch-changes/meta_raise_min_v1_16_0)

Unpin the meta dependency to allow the latest

---

lib/src/dart3_suggestors/null_safety_prep/state_mixin_suggestor.dart
lib/src/executables/null_safety_migrator_companion.dart
test/dart3_suggestors/null_safety_prep/state_mixin_suggestor_test.dart
test/executables/null_safety_migrator_companion_test.dart
test/test_fixtures/required_props/test_package/lib/src/test_state.dart

When working on a different codemod, we noticed that `ClassComponentRequiredInitialStateMigrator` migrates defaulted state mixin fields, but there's no codemod to migrate the rest of state mixin fields - we should add one to set all other fields to optional.
- Added `StateMixinSuggestor` to make all state mixin fields optional and run it after `ClassComponentRequiredInitialStateMigrator` …

FED-3248 Update non-defaulted state mixin fields to be optional

---

.github/workflows/dart_ci.yml
lib/src/dart3_suggestors/null_safety_prep/callback_ref_hint_suggestor.dart
lib/src/dart3_suggestors/null_safety_prep/class_component_required_default_props.dart
lib/src/dart3_suggestors/null_safety_prep/class_component_required_initial_state.dart
lib/src/dart3_suggestors/null_safety_prep/connect_required_props.dart
lib/src/dart3_suggestors/null_safety_prep/state_mixin_suggestor.dart
lib/src/dart3_suggestors/required_props/codemod/required_props_suggestor.dart
test/dart3_suggestors/null_safety_prep/callback_ref_hint_suggestor_test.dart
test/dart3_suggestors/null_safety_prep/class_component_required_default_props_test.dart
test/dart3_suggestors/null_safety_prep/class_component_required_initial_state_test.dart
test/dart3_suggestors/null_safety_prep/connect_required_props_test.dart
test/dart3_suggestors/null_safety_prep/state_mixin_suggestor_test.dart
test/executables/required_props_collect_and_codemod_test.dart
test/resolved_file_context.dart
test/test_fixtures/over_react_null_safe_project/README.md
test/test_fixtures/over_react_null_safe_project/lib/analysis_warmup.dart
test/test_fixtures/over_react_null_safe_project/lib/src/test_lang_version_comment.dart
test/test_fixtures/over_react_null_safe_project/lib/src/test_null_safe.dart
test/test_fixtures/over_react_null_safe_project/pubspec.yaml
test/util/component_usage_migrator_test.dart

During null safety migrations, some repos will be incrementally migrated, and there's a good chance the over_react null safety companion set of codemods (the one that inserts nullability hints) will get run on a mixture of not-yet-migrated and already-migrated code.
To avoid adding a bunch of nullability hints to files that have already been migrated to null safety, which would have to be manually removed, we should update our codemods to not run on files that are already null-safe.
- Add short circuit to all companion codemod suggestors if the file is already null safe
- Add tests
While we perform many automated checks before auto-merging, some …

FED-2554 Companion codemods should not run on null-safe files

---

CHANGELOG.md
pubspec.yaml

* [FED-3209 Remove explicit null passed to useRef](https://github.com/Workiva/over_react_codemod/pull/296)
* [FED-2994 Update class component defaults codemod to take public-ness into account](https://github.com/Workiva/over_react_codemod/pull/297)
* [FED-3248 Update non-defaulted state mixin fields to be optional](https://github.com/Workiva/over_react_codemod/pull/298)
* [Raise the react_material_ui dependency min to v1.214.2](https://github.com/Workiva/over_react_codemod/pull/300)
* [Unpin the meta dependency to allow the latest](https://github.com/Workiva/over_react_codemod/pull/301)
* [FED-3143 Null Safety Codemod for connect props](https://github.com/Workiva/over_react_codemod/pull/302)
* [FED-2554 Companion codemods should not run …

RM-276934 Release over_react_codemod 2.34.0

---

lib/src/executables/unify_package_rename.dart
lib/src/unify_package_rename_suggestors/constants.dart
lib/src/unify_package_rename_suggestors/import_renamer.dart
lib/src/unify_package_rename_suggestors/unify_rename_suggestor.dart
test/unify_package_rename_suggestors/import_renamer_test.dart
test/unify_package_rename_suggestors/unify_rename_suggestor_test.dart

Make some last updates to prep the rename codemod for the sourcegraph batch
- Update the codemod to:
- no longer make changes to import namespaces
- update `data_grid_premium.dart` entrypoint which is different on `unify_ui`
- update / add fixme comments to make sure everything that needs to be manually QAed has a comment saying so
- add `LinkButton` constants to list to be updated
- Update tests …

FED-3281 Update rename codemod

---

CHANGELOG.md
pubspec.yaml

* [FED-3281 Update rename codemod](https://github.com/Workiva/over_react_codemod/pull/305)
Requested by: @sydneyjodon-wk
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_codemod/compare/2.34.0...Workiva:release_over_react_codemod_2.35.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react_codemod/compare/2.34.0...2.35.0
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6153708125028352/?repo_name=Workiva%2Fover_react_codemod&pull_number=307)

RM-293191 Release over_react_codemod 2.35.0

---

pubspec.yaml
test/test_fixtures/required_props/test_package/pubspec.yaml

This PR raises the min version of meta to 1.16.0. Passing CI
[_Created by Sourcegraph batch change `Workiva/meta_raise_min_v1_16_0_really`._](https://workiva.sourcegraphcloud.com/organizations/Workiva/batch-changes/meta_raise_min_v1_16_0_really)

Raise the meta dependency min to v1.16.0

---

pubspec.yaml

This PR raises the max version of uuid to 5.0.0. Passing CI
[_Created by Sourcegraph batch change `Workiva/uuid_raise_max_v5_0_0`._](https://workiva.sourcegraphcloud.com/organizations/Workiva/batch-changes/uuid_raise_max_v5_0_0)

Raise the uuid dependency max to v5.0.0

---

pubspec.yaml

This PR raises the min version of uuid to 4.0.0. Passing CI
[_Created by Sourcegraph batch change `Workiva/uuid_raise_min_v4_0_0`._](https://workiva.sourcegraphcloud.com/organizations/Workiva/batch-changes/uuid_raise_min_v4_0_0)

Raise the uuid dependency min to v4.0.0

---

test/test_fixtures/wsd_project/pubspec.yaml

This PR widens the allowable version range of web_skin_dart so that all Dart repos at Workiva 
can consume version 3.0.0 without updating all repositories in lock step.
This major version removes the "v1" UI components that were deprecated over 4 years ago. 
**Since over_react_codemod 
[no longer has any usages of these deprecated components / entrypoints](https://workiva.sourcegraphcloud.com/search?q=context%3Adart-prod+web_skin_dart%5C%2F%28ui_compo%7Cdnd%7Cshared%7Ctoolbars%7Cforms%7Clayout%29&patternType=regexp&case=yes&sm=0&df=%5B%22repo%22%2C%22github.com%2FWorkiva%2Fover_react_codemod%22%2C%22repo%3A%5Egithub%5C%5C.com%2FWorkiva%2Fover_react_codemod%24%22%5D) 
it is safe to allow consumption of the web_skin_dart release that removed them (3.0.0).**
**These changes can be merged …

Allow consumption of web_skin_dart 3.0.0

---

test/test_fixtures/wsd_project/pubspec.yaml

This PR raises the min version of web_skin_dart to 3.0.0. Passing CI
[_Created by Sourcegraph batch change `Workiva/web_skin_dart_raise_min_v3_0_0`._](https://workiva.sourcegraphcloud.com/organizations/Workiva/batch-changes/web_skin_dart_raise_min_v3_0_0)

Raise the web_skin_dart dependency min to v3.0.0

---

CHANGELOG.md
pubspec.yaml

* [Raise the uuid dependency max to v5.0.0](https://github.com/Workiva/over_react_codemod/pull/313)
* [Raise the uuid dependency min to v4.0.0](https://github.com/Workiva/over_react_codemod/pull/314)
* [Allow consumption of web_skin_dart 3.0.0](https://github.com/Workiva/over_react_codemod/pull/315)
* [Raise the web_skin_dart dependency min to v3.0.0](https://github.com/Workiva/over_react_codemod/pull/316)
* [FED-3903 React 18 Upgrade Codemod](https://github.com/Workiva/over_react_codemod/pull/319)
Requested by: @sydneyjodon-wk
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_codemod/compare/2.36.0...Workiva:release_over_react_codemod_2.37.0
Diff Between Last Tag and New Tag: …

RM-302045 Release over_react_codemod 2.37.0
