Workiva/over_react_codemod

README.md

@corwinsheahan-wf @sebastianmalysa-wf @georgelesica-wf @maxwellpeterson-wf

AF-3923 Fix broken link in readme

---

example/README.md

@corwinsheahan-wf @sebastianmalysa-wf @georgelesica-wf @maxwellpeterson-wf

AF-3925 Add an example README for the pub site.

---

pubspec.yaml

* [AF-3923 Fix broken link in readme](https://github.com/Workiva/over_react_codemod/pull/16)
* [AF-3925 Add an example README for the pub site.](https://github.com/Workiva/over_react_codemod/pull/17)
* [AF-3985 Fix a bug with the UiFactoryIgnoreCommentRemover](https://github.com/Workiva/over_react_codemod/pull/18)
Requested by: @evan.weible
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_codemod/compare/1.0.0...Workiva:release_over_react_codemod_1.0.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react_codemod/compare/1.0.0...1.0.1

AF-3922 Release over_react_codemod 1.0.1

---

CHANGELOG.md
pubspec.yaml

* [RED-3217 - Add aviary.yaml](https://github.com/Workiva/over_react_codemod/pull/20)
* [CPLAT-4058 Provide additional --help output and better stderr](https://github.com/Workiva/over_react_codemod/pull/21)
Requested by: @evan.weible
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_codemod/compare/1.0.1...Workiva:release_over_react_codemod_1.0.2
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react_codemod/compare/1.0.1...1.0.2

CPLAT-3990 Release over_react_codemod 1.0.2

---

lib/src/react16_suggestors/react16_utilities.dart
lib/src/react16_suggestors/react_style_maps_updater.dart
test/react16_suggestors/react_style_maps_updater_test.dart

See https://github.com/Workiva/over_react_codemod/pull/30 for full PR description. This PR is simply meant to merge in Greg's suggestions for #30  

Style Map Codemod (Adding Greg's Suggestions)

---

lib/src/component2_suggestors/copyunconsumeddomprops_migrator.dart
lib/src/executables/component2_upgrade.dart
test/component2_suggestors/copyunconsumeddomprops_migrator_test.dart
test/util.dart

Because of Component to Component2 update, `copyUnconsumedDomProps` and `copyUnconsumedProps` usages need to be updated:
- Update copyUnconsumedDomProps usage:
`- ..addProps(copyUnconsumedDomProps())`
`+ ..modifyProps(addUnconsumedDomProps)`
- Update copyUnconsumedProps usage:
`- ..addProps(copyUnconsumedProps())`
`+ ..modifyProps(addUnconsumedProps)`
- Add suggestor that updates `copyUnconsumedDomProps` and `copyUnconsumedProps` usages.
- Write tests.
@kealjones-wk @aaronlademann-wf @greglittlefield-wf @joebingham-wk  …

CPLAT-6814 Update copyUnconsumedDomProps usage

---

pubspec.yaml

* [CPLAT-3300: CP Code Review and PR Merging Team agreement update](https://github.com/Workiva/over_react_codemod/pull/29)
* [CPLAT-5806 React 16 Upgrade Codemod](https://github.com/Workiva/over_react_codemod/pull/38)
* [CPLAT-6495 Codemod for Updating React Pubspec Dependency](https://github.com/Workiva/over_react_codemod/pull/39)
* [CPLAT-5212 Codemod to convert from UiComponent to UiComponent2](https://github.com/Workiva/over_react_codemod/pull/40)
* [CPLAT-7089: Add a pubspec.yaml check for react/over_react versions before running](https://github.com/Workiva/over_react_codemod/pull/45)
Requested by: @kealjones-wk
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_codemod/compare/1.1.0...Workiva:release_o …

CPLAT-4452 Release over_react_codemod 1.2.0

---

CHANGELOG.md
pubspec.yaml

* [Fix for version "any"](https://github.com/Workiva/over_react_codemod/pull/53)
Requested by: @kealjones-wk
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_codemod/compare/1.3.0...Workiva:release_over_react_codemod_1.3.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react_codemod/compare/1.3.0...1.3.1

RM-57970 Release over_react_codemod 1.3.1

---

bin/react16_post_rollout_cleanup.dart
lib/src/component2_suggestors/component2_utilities.dart
lib/src/executables/react16_post_rollout_cleanup.dart
lib/src/executables/react16_upgrade.dart
lib/src/react16_suggestors/comment_remover.dart
lib/src/react16_suggestors/constants.dart
lib/src/react16_suggestors/react16_utilities.dart
lib/src/react16_suggestors/react_style_maps_updater.dart
pubspec.yaml
test/react16_suggestors/comment_remover_test.dart
test/react16_suggestors/react_style_maps_updater_test.dart

We need a codemod that can remove React 16 progress comments and update the pubspec dependencies.
- Add a suggestor for removing comments
- Add a new executable
- Add tests
@aaronlademann-wf @kealjones-wk @greglittlefield-wf @sydneyjodon-wk 

CPLAT-6933 React 16 Post Rollout Codemod

---

pubspec.yaml

* [CPLAT-7175 Update componentWillMount Suggestor](https://github.com/Workiva/over_react_codemod/pull/49)
* [CPLAT-7173 Add getDefaultProps getInitialState Migrators](https://github.com/Workiva/over_react_codemod/pull/56)
* [CPLAT-6933 React 16 Post Rollout Codemod](https://github.com/Workiva/over_react_codemod/pull/57)
* [React 16 testing dependency logic update](https://github.com/Workiva/over_react_codemod/pull/60)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_codemod/compare/1.3.2...Workiva:release_over_react_codemod_1.4.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react_codemod/compare/1.3.2...1.4.0
The logs for the request that created this …

RM-58733 Release over_react_codemod 1.4.0

---

lib/src/react16_suggestors/react_dom_render_migrator.dart
lib/src/util/component_usage.dart
test/react16_suggestors/react_dom_render_migrator_test.dart

over_react_codemod's ErrorBoundary codemod short-cirtcuits if it can't find a react_dom.dart import.
However, for part files, this import never exists.
AC
- Update logic to not rely on react_dom import. If none is found, assume the namespace is react_dom.
- Update import insertion logic to not insert import within part files, since that would be invalid.
- Allow react_dom import from `over_react`
- Add test cases for part files …

CPLAT-7863: Update logic to not rely on imports and allows over_react import

---

lib/src/react16_suggestors/comment_remover.dart
lib/src/react16_suggestors/react_dom_render_migrator.dart

Lints suck
- Removes unused imports.

Just cleanup some unused import lints

---

pubspec.yaml

* [CPLAT-8187 Use caret deps when possible in version range updates](https://github.com/Workiva/over_react_codemod/pull/69)
Requested by: @greglittlefield-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_codemod/compare/1.4.3...Workiva:release_over_react_codemod_1.5.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react_codemod/compare/1.4.3...1.5.0

RM-60035 Release over_react_codemod 1.5.0

---

lib/src/boilerplate_suggestors/advanced_props_and_state_class_migrator.dart
lib/src/boilerplate_suggestors/annotations_remover.dart
lib/src/boilerplate_suggestors/boilerplate_utilities.dart
lib/src/boilerplate_suggestors/props_mixins_migrator.dart
lib/src/boilerplate_suggestors/simple_props_and_state_class_migrator.dart
test/boilerplate_suggestors/advanced_props_and_state_class_migrator_test.dart
test/boilerplate_suggestors/annotations_remover_test.dart
test/boilerplate_suggestors/boilerplate_utilities_test.dart
test/boilerplate_suggestors/props_mixin_migrator_test.dart
test/util.dart

Some edge cases have been discovered as more rollout testing is being performed on the new boilerplate codemods.
Address / add test coverage for those edge cases.
Please review: @greglittlefield-wf @joebingham-wk @sydneyjodon-wk 

CPLAT-10081 Address some boilerplate codemod edge cases

---

docs/boilerplate_upgrade.md
lib/src/boilerplate_suggestors/advanced_props_and_state_class_migrator.dart
lib/src/boilerplate_suggestors/boilerplate_utilities.dart
lib/src/boilerplate_suggestors/migration_decision.dart
lib/src/component2_suggestors/componentdidupdate_migrator.dart
lib/src/component2_suggestors/componentwillmount_migrator.dart
lib/src/component2_suggestors/copyunconsumeddomprops_migrator.dart
lib/src/component2_suggestors/defaultprops_initialstate_migrator.dart
lib/src/component2_suggestors/deprecated_lifecycle_suggestor.dart
lib/src/component2_suggestors/setstate_updater.dart
lib/src/executables/boilerplate_upgrade.dart
lib/src/util.dart
pubspec.yaml
test/boilerplate_suggestors/advanced_props_and_state_class_migrator_test.dart
test/boilerplate_suggestors/simple_props_and_state_class_migrator_test.dart
test/util_test.dart

There were some things I came across during rollout that I wanted to tweak the codemod to fix.
- Fix issue with FIXME comments being added multiple times
- Don't put FIXME comments between node and annotation since it makes things harder to read
- Make the first sentence of FIXMEs that will remain in the code be all on one line, so they can be seen in an IDE's "TODO" view without going to the source
- Move FIXME instructions into a markdown file and link to that instead, so that code isn't as cluttered after running the codemod.
- Don't factor whether mixins have been converted into migration decision, since they're forwards compatible
- Generalize version constraint updating, add workiva_analysis_options to the list of dependencies that are added
- Use build_vm_compilers so that tests …

CPLAT-10914 Fix issues discovered during initial boilerplate rollout

---

docs/boilerplate_upgrade.md

Add additional paths forward for components requiring breaking changes before upgrading

---

lib/src/boilerplate_suggestors/annotations_remover.dart
lib/src/boilerplate_suggestors/boilerplate_utilities.dart
lib/src/boilerplate_suggestors/constants.dart
lib/src/boilerplate_suggestors/migration_decision.dart
lib/src/component2_suggestors/class_name_and_annotation_migrator.dart
lib/src/component2_suggestors/component2_utilities.dart
lib/src/util/component_usage.dart
test/component2_suggestors/component2_utilities_test.dart

There were a handful of issues I ran into, either during last stretch of component migration or after the migration was finished, that could be fixed with some small changes.
- Treat FIXMEs converted to TODOs the same as FIXMEs (and don't add new FIXMEs on top of them)
- Fix locally-generated semver reports not being readable due to not being nested inside an `{"exports": ...}` object
- Account for edge cases when Props were named `${componentName}ComponentProps`
- Ignore common mixins that are known to not implement lifecycle methods and thus shouldn't require necessitate migration:
- FocusRestorer/FormControlApi/FormControlApiV2/TypedSnapshot
- Update minimum versions of over_react/over_react_test to include important bugfixes
(same as changes)
_[See …

More tweaks/improvements to boilerplate codemod

---

lib/src/util.dart

There has been at least once consumer report of the `boilerplate_upgrade` codemod failing due to a null error accessing `isEof`: 
```
[SEVERE] Suggestor.generatePatches() threw unexpectedly.
NoSuchMethodError: The getter 'isEof' was called on null.
Receiver: null
Tried calling: isEof
```
I'm not sure exactly what is causing this to occur since I'm not very familiar with these codemods, but this should work around the issue.  …

Handle null token

---

CHANGELOG.md
pubspec.yaml

* [Handle null token](https://github.com/Workiva/over_react_codemod/pull/100)
Requested by: @corwinsheahan-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_codemod/compare/1.8.0...Workiva:release_over_react_codemod_1.9.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react_codemod/compare/1.8.0...1.9.0

RM-85779 Release over_react_codemod 1.9.0

---

.github/workflows/dart_ci.yml

Because Dart 2.14.2 and Dart 2.12.0 have different formatting expectations, the formatting step will always fail on Dart stable (example PR: https://github.com/Workiva/over_react_codemod/pull/121)
- Move formatting check to Dart 2.12 only

Only check formatting in CI on Dart 2.12

---

lib/src/executables/rmui_bundle_migration.dart
lib/src/rmui_bundle_suggestors/constants.dart
lib/src/rmui_bundle_suggestors/dart_script_adder.dart
lib/src/rmui_bundle_suggestors/html_script_adder.dart
lib/src/util.dart
test/rmui_bundle_suggestors/dart_script_adder_test.dart
test/rmui_bundle_suggestors/html_script_adder_test.dart
test/util.dart

> This PR will be merged into #124 (the RMUI bundle codemod base branch)
We need a suggestor that adds the RMUI bundle in the following places:
- HTML files (in example, web, test, etc.)
- HTML test template files 
- (these may not always have the same extension, but seem to usually at least have `.html` in the filename)
- Dart tools that generate these files (usually dependencies are a script tag in a Dart string in an array; see above query for examples)
- It'll probably be easier to handle any edge-cases by hand, since we'll have to manually regenerate the files anyways
Looking for the react-dart script and adding the RMUI script afterwards is probably going to be the easiest way to accomplish this.
The best way we've thought of so far to identify these files is to search for …

CPLAT-15684 Suggestors to add RMUI bundle to HTML/Dart files

---

pubspec.yaml

* [Upgrade to codemod v0.3.0 (not yet published)](https://github.com/Workiva/over_react_codemod/pull/111)
* [CPLAT-15326 Enable null safety](https://github.com/Workiva/over_react_codemod/pull/118)
* [Update Dart base images to the latest releases](https://github.com/Workiva/over_react_codemod/pull/120)
* [Only check formatting in CI on Dart 2.12](https://github.com/Workiva/over_react_codemod/pull/123)
* [CPLAT-15670 RMUI Bundle Codemod](https://github.com/Workiva/over_react_codemod/pull/124)
* [CPLAT-15683 Add dependency_validator updaters](https://github.com/Workiva/over_react_codemod/pull/128)
* [CPLAT-15826 Codemod to add `ThemeProvider` to `react_dom.render`](https://github.com/Workiva/over_react_codemod/pull/129)
Requested by: …

RM-109954 Release over_react_codemod 2.0.0

---

pubspec.yaml

* Minor changes:
* [CPLAT-14830 CPLAT-15336 MUI migration codemod](https://github.com/Workiva/over_react_codemod/pull/125)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_codemod/compare/2.0.0...Workiva:release_over_react_codemod_2.1.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react_codemod/compare/2.0.0...2.1.0
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6153708125028352/?pull_number=135&repo_name=Workiva%2Fover_react_codemod)

RM-118583 Release over_react_codemod 2.1.0

---

.github/workflows/dart_ci.yml
dart_dependency_validator.yaml
pubspec.yaml

* [CPLAT-16174 Fix dynamic calls involving toBuilder() being detected as unresolved usages](https://github.com/Workiva/over_react_codemod/pull/136)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_codemod/compare/2.1.0...Workiva:release_over_react_codemod_2.1.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react_codemod/compare/2.1.0...2.1.1
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6153708125028352/?pull_number=137&repo_name=Workiva% …

RM-121124 Release over_react_codemod 2.1.1

---

lib/src/mui_suggestors/components.dart
lib/src/mui_suggestors/components/mui_inline_alert_migrator.dart
lib/src/util.dart
lib/src/util/component_usage_migrator.dart
test/mui_suggestors/components/mui_inline_alert_migrator_test.dart
test/util/component_usage_migrator_test.dart

We need a migrator for alerts! The added migrator will only attempt to migrate those that are `inline` and do not have any non-inline props.
- Add an alert migrator
- Add a new `yieldAddChildPatch` utility
- Add tests

CPLAT-15338 Alert Migrator

---

lib/src/executables/intl_message_migration.dart
lib/src/intl_suggestors/intl_migrator.dart
lib/src/intl_suggestors/utils.dart

Address CR items from INTL-2
Add some doc comments.
Clean up some logic.
Use some cleaner code patterns I was unaware of.

INTL-4 Address follow up items

---

pubspec.yaml

* [CPLAT-15338 Alert Migrator](https://github.com/Workiva/over_react_codemod/pull/139)
* [Fix wildcard to include branch names with slashes](https://github.com/Workiva/over_react_codemod/pull/141)
* [INTL-2 Intl Migrator](https://github.com/Workiva/over_react_codemod/pull/142)
* [Replace deprecated commands with new dart commands](https://github.com/Workiva/over_react_codemod/pull/143)
* [Update references to the archived slack room #support-client-plat](https://github.com/Workiva/over_react_codemod/pull/144)
* [INTL-4 Address follow up items](https://github.com/Workiva/over_react_codemod/pull/145)
Requested by: @matthewward-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_codemod/compare/2.1.1...Workiv …

RM-124258 Release over_react_codemod 2.2.0

---

pubspec.yaml

* [Fix intl_message_migration issue with Windows ](https://github.com/Workiva/over_react_codemod/pull/157)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_codemod/compare/2.2.1...Workiva:release_over_react_codemod_2.3.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react_codemod/compare/2.2.1...2.3.0
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6153708125028352/?pull_number=158&repo_name=Workiva%2Fover_react_codemod)

RM-149630 Release over_react_codemod 2.3.0

---

pubspec.yaml

* [INTL-71 Handle lib filepath exception](https://github.com/Workiva/over_react_codemod/pull/156)
* [INTL-67: Avoid using Glob with absolute packageRoots, problematic on Windows](https://github.com/Workiva/over_react_codemod/pull/159)
* [INTL-78: Exclude some bad cases from intl_message_migration](https://github.com/Workiva/over_react_codemod/pull/160)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_codemod/compare/2.3.0...Workiva:release_over_react_codemod_2.4.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react_codemod/compare/2.3.0...2.4.0
The logs for the request that created this PR can be found …

RM-151651 Release over_react_codemod 2.4.0

---

pubspec.yaml

* [INTL-115: Make the intl_message_migration also look for likely user-visible String constants](https://github.com/Workiva/over_react_codemod/pull/161)
* [INTL-114: Comment out the code for adding a FIXME on the label attribute](https://github.com/Workiva/over_react_codemod/pull/164)
* [INTL-116: Always use {} around variable names in the generated code](https://github.com/Workiva/over_react_codemod/pull/165)
* [INTL-117: Add a functional test for intl_message_migration](https://github.com/Workiva/over_react_codemod/pull/166)
* [INTL-121: Allow specifying paths on the command line](https://github.com/Workiva/over_react_codemod/pull/167)
Diff Between Last Tag and Proposed Release: …

RM-153617 Release over_react_codemod 2.5.0

---

pubspec.yaml

* [INTL-128: intl_message_migration should handle adjacent strings, exclude strings with no alphabetics](https://github.com/Workiva/over_react_codemod/pull/169)
* [INTL-127: Fix intl_message_migration function numbering](https://github.com/Workiva/over_react_codemod/pull/170)
* [INTL-132: intl_message_migration should only do the lib directory by default, allow specifying others](https://github.com/Workiva/over_react_codemod/pull/171)
* [Add CHANGELOG entries for 2.6.0 release](https://github.com/Workiva/over_react_codemod/pull/172)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_codemod/compare/2.5.0...Workiva:release_over_react_codemod_2.6.0
Diff Between Last Tag and New …

RM-154828 Release over_react_codemod 2.6.0

---

pubspec.yaml

* [INTL-136: Ignore the lint for unnecessary braces in string interpolation in the intl.dart class](https://github.com/Workiva/over_react_codemod/pull/174)
* [INTL-137: intl_message_migration uses the variable name for constant strings](https://github.com/Workiva/over_react_codemod/pull/175)
* [INTL-139: intl_message_migration: Split out explicit file access, step towards running repeatedly](https://github.com/Workiva/over_react_codemod/pull/176)
* [Update references to the previous team name](https://github.com/Workiva/over_react_codemod/pull/177)
* [Fixes problem with adjacent string and duplicated constant names](https://github.com/Workiva/over_react_codemod/pull/178)
Diff Between Last Tag and Proposed …

RM-155794 Release over_react_codemod 2.7.0

---

pubspec.yaml

* [INTL-65: Read and preserve existing messages in intl_message_migration](https://github.com/Workiva/over_react_codemod/pull/182)
* [Turn on the --migrate-constants option by default](https://github.com/Workiva/over_react_codemod/pull/183)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_codemod/compare/2.8.0...Workiva:release_over_react_codemod_2.9.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react_codemod/compare/2.8.0...2.9.0
This pull request can be recreated by clicking …

RM-159590 Release over_react_codemod 2.9.0

---

CHANGELOG.md
lib/src/intl_suggestors/message_parser.dart
lib/src/intl_suggestors/utils.dart

When intl_message_migration produces invalid source code for a method it crashes without actually telling you what the source code was.
print the source code

Report parse errors better

---

pubspec.yaml

* [Update to analyzer v2](https://github.com/Workiva/over_react_codemod/pull/185)
* [INTL-188: Fix incrementing the usage number of duplicate getters](https://github.com/Workiva/over_react_codemod/pull/186)
* [Handle explicit newlines in strings](https://github.com/Workiva/over_react_codemod/pull/187)
* [Report parse errors better](https://github.com/Workiva/over_react_codemod/pull/188)
* [Do not internationalize SCREAMING_CAPS constants](https://github.com/Workiva/over_react_codemod/pull/189)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_codemod/compare/2.9.0...Workiva:release_over_react_codemod_2.10.0
Diff Between Last Tag and New Tag: …

RM-160644 Release over_react_codemod 2.10.0

---

pubspec.yaml

* [INTL-176: Ignore statement or file](https://github.com/Workiva/over_react_codemod/pull/191)
* [INTL-346: Use the W_intl wrapper class in the codemod](https://github.com/Workiva/over_react_codemod/pull/194)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_codemod/compare/2.10.0...Workiva:release_over_react_codemod_2.11.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react_codemod/compare/2.10.0...2.11.0
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerRelea …

RM-163393 Release over_react_codemod 2.11.0

---

pubspec.yaml

* [Add a --migrate-components option](https://github.com/Workiva/over_react_codemod/pull/196)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_codemod/compare/2.11.0...Workiva:release_over_react_codemod_2.12.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react_codemod/compare/2.11.0...2.12.0
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6153708125028352/?repo_name=Workiva%2Fover_react_codemod&pull_number=197)

RM-167784 Release over_react_codemod 2.12.0

---

pubspec.yaml

* [INTL-174 : Add nicer logging to codemod dryrun check](https://github.com/Workiva/over_react_codemod/pull/200)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_codemod/compare/2.13.0...Workiva:release_over_react_codemod_2.14.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react_codemod/compare/2.13.0...2.14.0
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6153708125028352/?repo_name=Workiva%2Fover_react_codemod&pull_number=202)

RM-170618 Release over_react_codemod 2.14.0

---

README.md
docs/intl_message.md

These notes are intended to help those using the `intl_message_migration` codemod.
- updates to Readme
Update Readme
- docs only change

INTL-1021 :Notes on INTL Message Codemod

---

pubspec.yaml

* [INTL-1021 :Notes on INTL Message Codemod](https://github.com/Workiva/over_react_codemod/pull/207)
* [Pin mockito 5](https://github.com/Workiva/over_react_codemod/pull/208)
* [INTL-1090 Migrate calls to addContextMenuItem](https://github.com/Workiva/over_react_codemod/pull/209)
* [INTL-1071 Add a --no-migrate option that just sorts and possibly prunes](https://github.com/Workiva/over_react_codemod/pull/210)
* [INTL-1109: Fix the ignore for static-only classes to be for the file](https://github.com/Workiva/over_react_codemod/pull/211)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_codemod/compare/2.14.0...Workiva:release_over_react_codemod_2.15.0
Diff Between Last Tag and …

RM-170819 Release over_react_codemod 2.15.0

---

pubspec.yaml

* [FED-1143: Batch change to update consumers to new RMUI ESM bundle](https://github.com/Workiva/over_react_codemod/pull/212)
Requested by: @annawatson-wk
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_codemod/compare/2.15.0...Workiva:release_over_react_codemod_2.16.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react_codemod/compare/2.15.0...2.16.0
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6153708125028352/?repo_name=Workiva%2Fover_react_codemod&pull_number=214) …

RM-185185 Release over_react_codemod 2.16.0

---

pubspec.yaml

* [FED-1237: add shouldAddDependencies](https://github.com/Workiva/over_react_codemod/pull/217)
Requested by: @annawatson-wk
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_codemod/compare/2.17.0...Workiva:release_over_react_codemod_2.18.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react_codemod/compare/2.17.0...2.18.0
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6153708125028352/?repo_name=Workiva%2Fover_react_codemod&pull_number=218)

RM-187622 Release over_react_codemod 2.18.0

---

pubspec.yaml

* [The glob for pubspecs would pick up things like empty_pubspec.yaml](https://github.com/Workiva/over_react_codemod/pull/219)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_codemod/compare/2.18.0...Workiva:release_over_react_codemod_2.19.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react_codemod/compare/2.18.0...2.19.0
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6153708125028352/?repo_name=Workiva%2Fover_react_codemod&pull_number=220 …

RM-187996 Release over_react_codemod 2.19.0

---

lib/src/executables/intl_message_migration.dart
lib/src/intl_suggestors/intl_messages.dart
test/executables/intl_message_migration_test.dart
test/intl_suggestors/constant_migrator_test.dart
test/intl_suggestors/intl_configs_migrator_test.dart
test/intl_suggestors/intl_messages_test.dart
test/intl_suggestors/intl_migrator_test.dart

There are still too many merge conflicts on _intl.dart files. 
- Automatically call 'dart_dev format' on the file. If that fails (most commonly because the repo is not set up for dart_dev) print an error message at the end.
- Put an extra line break between methods to make it less confusing for the merge algorithm. 

INTL-1228: Attempt to reduce merge conflicts on _intl.dart files

---

pubspec.yaml

* [INTL-1228: Attempt to reduce merge conflicts on _intl.dart files](https://github.com/Workiva/over_react_codemod/pull/221)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_codemod/compare/2.19.0...Workiva:release_over_react_codemod_2.20.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react_codemod/compare/2.19.0...2.20.0
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6153708125028352/?repo_name=Workiva%2Fover_react_codemod&pull_number=222)

RM-188451 Release over_react_codemod 2.20.0

---

pubspec.yaml

* [INTL-1250: Fix for creating two copies of identical messages when they used double quotes](https://github.com/Workiva/over_react_codemod/pull/225)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_codemod/compare/2.21.0...Workiva:release_over_react_codemod_2.22.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react_codemod/compare/2.21.0...2.22.0
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6153708125028352/?repo_name=Workiva%2Fover_react_c …

RM-190424 Release over_react_codemod 2.22.0

---

pubspec.yaml

* [INTL-1311:Add an explanatory comment on codemod-generated files](https://github.com/Workiva/over_react_codemod/pull/230)
* [INTL-1294: Implement ignore comments for const strings](https://github.com/Workiva/over_react_codemod/pull/233)
* [INTL-1363 : Give a better error message when something in the intl file is not a method](https://github.com/Workiva/over_react_codemod/pull/234)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_codemod/compare/2.23.0...Workiva:release_over_react_codemod_2.24.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react_codemod/compare/2.23.0...2.24.0
The logs for the request that created this PR can be found …

RM-196484 Release over_react_codemod 2.24.0

---

pubspec.yaml

* [INTL-231: Try checking for ignore lines within components](https://github.com/Workiva/over_react_codemod/pull/236)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_codemod/compare/2.24.0...Workiva:release_over_react_codemod_2.25.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react_codemod/compare/2.24.0...2.25.0
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6153708125028352/?repo_name=Workiva%2Fover_react_codemod&pull_number=237)

RM-203113 Release over_react_codemod 2.25.0

---

pubspec.yaml

* [Avoid meta 1.10.0](https://github.com/Workiva/over_react_codemod/pull/240)
* [INTL-1591: Handle non-arrow intl functions](https://github.com/Workiva/over_react_codemod/pull/244)
* [FEDX-405 : Update the analyzer to min 5.0.0](https://github.com/Workiva/over_react_codemod/pull/248)
* [INTL-1626: Multi line ignore comments](https://github.com/Workiva/over_react_codemod/pull/250)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_codemod/compare/2.26.0...Workiva:release_over_react_codemod_2.27.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react_codemod/compare/2.26.0...2.27.0
The logs for the request that created this PR can be found …

RM-211700 Release over_react_codemod 2.27.0

---

pubspec.yaml

* [INTL-1677: Exclude Pendo ID pattern in codemod](https://github.com/Workiva/over_react_codemod/pull/255)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_codemod/compare/2.27.0...Workiva:release_over_react_codemod_2.28.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react_codemod/compare/2.27.0...2.28.0
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6153708125028352/?repo_name=Workiva%2Fover_react_codemod&pull_number=256)

RM-219216 Release over_react_codemod 2.28.0

---

pubspec.yaml

* [INTL-1332: Add import smarts to codemod](https://github.com/Workiva/over_react_codemod/pull/241)
* [INTL-1608 : Activate _over_react_codemod executables separately](https://github.com/Workiva/over_react_codemod/pull/246)
* [FED-570 Unify package rename codemod](https://github.com/Workiva/over_react_codemod/pull/251)
* [Dart 2.19](https://github.com/Workiva/over_react_codemod/pull/260)
* [FED-1919 Codemod to add required flux actions / store prop(s)](https://github.com/Workiva/over_react_codemod/pull/268)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_codemod/compare/2.29.0...Workiva:release_over_react_codemod_2.30.0
Diff Between Last Tag and New Tag: …

RM-220915 Release over_react_codemod 2.30.0

---

pubspec.yaml

* [Raise the meta dependency min to v1.16.0](https://github.com/Workiva/over_react_codemod/pull/309)
* [raise_min_dart_sdk_2_19](https://github.com/Workiva/over_react_codemod/pull/311)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_codemod/compare/2.35.0...Workiva:release_over_react_codemod_2.36.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react_codemod/compare/2.35.0...2.36.0
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/615370812502835 …

RM-294811 Release over_react_codemod 2.36.0
